// vitest.config.ts  (repository root) — Vitest 4
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // A test file that matches nothing is a silent hole in a gate.
    passWithNoTests: false,
    // `.only` committed to main turns a 400-case suite into a 1-case suite that still prints green.
    allowOnly: false,
    // Flaky-by-retry is a way of not fixing a bug. Zero, everywhere, always.
    retry: 0,
    testTimeout: 10_000,
    hookTimeout: 30_000,
    // Deterministic file order so a golden-fixture failure reproduces from the printed seed.
    sequence: { shuffle: false, concurrent: false },
    reporters: process.env.CI ? ["default", "junit"] : ["default"],
    outputFile: { junit: "./reports/junit.xml" },
    coverage: {
      // Istanbul, not v8: V8 native coverage needs node:inspector, which the
      // workerd pools do not implement (@cloudflare/vitest-plugin rejects it).
      // Istanbul instruments the source, so one provider serves both tiers.
      provider: "istanbul",
      reporter: ["text-summary", "json-summary", "lcov"],
      reportsDirectory: "./coverage",
      all: true,
      // The measurement set is the packages whose §17.14 floor has ACTIVATED
      // (a floor exists from the milestone that introduces it — earlier
      // milestones only ship stubs, and the global floor cannot apply to
      // code a later milestone owns). Widen this list when a floor activates:
      // M5 adds packages/kernel, M6 apps/{mcp,worker}, M8 packages/x402, …
      include: [
        "packages/content/src/**/*.ts",
        "packages/kernel/src/**/*.ts",
        "packages/connectors/src/**/*.ts",
        "apps/edge/src/**/*.ts",
        "apps/web/proxy.ts",
      ],
      exclude: [
        "**/*.d.ts",
        "**/worker-configuration.d.ts", // generated by `wrangler types`
        "packages/schema/src/database.types.ts", // generated by `supabase gen types`
        "apps/edge/src/guards/forbid.ts", // a module whose only statement is `throw`
        "**/test/**",
        "**/dist/**",
        "**/.wrangler/**",
      ],
      thresholds: {
        // Global floor. Per-package floors follow §17.14 — vitest 4 has no
        // per-project coverage config, so per-glob keys here are their
        // equivalent (D32). New milestones add their floor on activation.
        statements: 80,
        branches: 75,
        functions: 80,
        lines: 80,
        "packages/content/src/**": {
          statements: 92,
          branches: 88,
          functions: 92,
          lines: 92,
        },
        "packages/kernel/src/**": {
          statements: 95,
          branches: 92,
          functions: 95,
          lines: 95,
          perFile: true,
        },
        "packages/connectors/src/**": {
          statements: 85,
          branches: 80,
          functions: 85,
          lines: 85,
        },
        "apps/edge/src/**": {
          statements: 90,
          branches: 85,
          functions: 90,
          lines: 90,
          perFile: true,
        },
        "apps/web/proxy.ts": {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
        },
      },
    },
    projects: [
      // Node tier: the pure packages, as they have always run.
      "packages/*/vitest.config.ts",
      // workerd tier: the SAME pure packages a second time (§17.1.2), plus the three Workers.
      "packages/*/vitest.workers.config.ts",
      "apps/edge/vitest.config.ts",
      "apps/mcp/vitest.config.ts",
      "apps/worker/vitest.config.ts",
      "apps/web/vitest.config.ts",
      // The spine lint rules ship with RuleTester suites; G-TEST must reach them too.
      "tools/eslint-plugin-musebook/vitest.config.ts",
    ],
  },
});
