// vitest.config.ts  (repository root) — Vitest 4
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    // A test file that matches nothing is a silent hole in a gate.
    passWithNoTests: false,
    // `.only` committed to main turns a 400-case suite into a 1-case suite that still prints green.
    allowOnly: false,
    // Flaky-by-retry is a way of not fixing a bug. Zero, everywhere, always.
    retry: 0,
    testTimeout: 10_000,
    hookTimeout: 30_000,
    // Deterministic file order so a golden-fixture failure reproduces from the printed seed.
    sequence: { shuffle: false, concurrent: false },
    reporters: process.env.CI ? ["default", "junit"] : ["default"],
    outputFile: { junit: "./reports/junit.xml" },
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "json-summary", "lcov"],
      reportsDirectory: "./coverage",
      all: true,
      include: ["packages/*/src/**/*.ts", "apps/*/src/**/*.ts"],
      exclude: [
        "**/*.d.ts",
        "**/worker-configuration.d.ts", // generated by `wrangler types`
        "packages/schema/src/database.types.ts", // generated by `supabase gen types`
        "apps/edge/src/guards/forbid.ts", // a module whose only statement is `throw`
        "**/test/**",
        "**/dist/**",
        "**/.wrangler/**",
      ],
      thresholds: {
        // Global floor. Per-package floors are set in each project config (§17.14).
        statements: 80,
        branches: 75,
        functions: 80,
        lines: 80,
      },
    },
    projects: [
      // Node tier: the pure packages, as they have always run.
      "packages/*/vitest.config.ts",
      // workerd tier: the SAME pure packages a second time (§17.1.2), plus the three Workers.
      "packages/*/vitest.workers.config.ts",
      "apps/edge/vitest.config.ts",
      "apps/mcp/vitest.config.ts",
      "apps/worker/vitest.config.ts",
      "apps/web/vitest.config.ts",
      // The spine lint rules ship with RuleTester suites; G-TEST must reach them too.
      "tools/eslint-plugin-musebook/vitest.config.ts",
    ],
  },
});
