// apps/edge/src/routes/robots-txt.ts — §7.14's canonical body, verbatim.
// `Sitemap:` is the only line that interpolates; every crawler stanza and the
// AIPREF `Content-Usage` declarations are literal.
import { cacheHeadersFor } from "../http/cache.js";
import { canonicalOrigin } from "../index.js";

const BODY = (origin: string): string =>
  [
    "# https://musebook.dev/robots.txt — generated by musebook-edge, do not edit by hand",
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /pay/",
    "Disallow: /oauth/",
    "Disallow: /compose",
    "Disallow: /settings",
    `Sitemap: ${origin}/sitemap.xml`,
    "",
    "# IETF AIPREF usage preferences. These apply only to paths that Allow/Disallow",
    "# already permits. Ordering carries no meaning. Crawlers may cache this file for",
    "# up to 24 hours, so the per-response Content-Usage header is authoritative.",
    "Content-Usage: /p/ train-ai=n",
    "Content-Usage: /p/ ai-use=n",
    "Content-Usage: /p/ search=y",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "Content-Usage: train-ai=n",
    "",
    "User-agent: Claude-User",
    "Allow: /",
    "Content-Usage: ai-use=y",
    "",
    "User-agent: Claude-SearchBot",
    "Allow: /",
    "Content-Usage: search=y",
    "",
    "User-agent: GPTBot",
    "Allow: /",
    "Content-Usage: train-ai=n",
    "",
    "User-agent: OAI-SearchBot",
    "Allow: /",
    "Content-Usage: search=y",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "Content-Usage: ai-use=y",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "Content-Usage: ai-use=y",
    "",
    "User-agent: Google-Extended",
    "Allow: /",
    "Content-Usage: train-ai=n",
    "",
    "User-agent: meta-externalagent",
    "Allow: /",
    "Content-Usage: train-ai=n",
    "",
    "User-agent: Bytespider",
    "Disallow: /",
    "",
    "User-agent: CCBot",
    "Disallow: /p/",
    "",
  ].join("\n");

export function robotsTxt(req: Request): Response {
  return new Response(BODY(canonicalOrigin(new URL(req.url))), {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      ...cacheHeadersFor({ shared: true, sMaxAge: 3600, swr: 86_400 }),
    },
  });
}
