// packages/classify/src/client.ts
import { TypeSafeClient, type Fetch, type LogLevel } from "@typesafe-ai/sdk";

/** Only the fields this package reads. The Worker's full Env lives in
 *  apps/worker/worker-configuration.d.ts, generated by `wrangler types` (§3.6). */
export type ClassifyEnv = {
  TYPESAFE_API_KEY?: string;
  TYPESAFE_BASE_URL?: string;
  TYPESAFE_DEFAULT_MODEL?: string;
  TYPESAFE_LOG_LEVEL?: string;
  CLASSIFY_TAXONOMY_MODE?: string;
};

/**
 * Deploy-time safety without a deploy-time failure. Constructed lazily so a
 * Worker that never processes a classify message can still deploy with the
 * secret unset — the SDK throws TypeSafeError if the key is missing, and it is
 * thrown at first use, not at import.
 *
 * `timeout` is PER ATTEMPT, not per request (§8.9's budget table). The SDK's own
 * retry — two more attempts by default — is what survives a flaky 429; the
 * queue's retry is what survives an outage. Both exist because they mean
 * different things.
 */
export function makeClient(env: ClassifyEnv, fetchImpl?: Fetch): TypeSafeClient {
  return new TypeSafeClient({
    ...(env.TYPESAFE_API_KEY ? { apiKey: env.TYPESAFE_API_KEY } : {}),
    ...(env.TYPESAFE_BASE_URL ? { baseURL: env.TYPESAFE_BASE_URL } : {}),
    ...(env.TYPESAFE_DEFAULT_MODEL ? { defaultModel: env.TYPESAFE_DEFAULT_MODEL } : {}),
    logLevel: (env.TYPESAFE_LOG_LEVEL as LogLevel | undefined) ?? "warn",
    timeout: 30_000,
    ...(fetchImpl ? { fetch: fetchImpl } : {}),
  });
}
