// GENERATED from the sibling .sql files — edit those, then re-run scripts/gen-sql-index.
// Inlined because neither esbuild nor vitest resolves .sql imports without loader config.

const agentAuthoredSql =
  "-- §9.7 AgentAuthoredSource: agent-authored posts whose identity is not blocked.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.agent_identities ai on ai.id = p.posted_by_agent_id\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.posted_by_agent_id is not null\n   and ai.is_blocked = false\n   and p.published_at > now() - interval '14 days'\n   and ($1::post_kind[] is null or p.kind = any($1))\n order by p.published_at desc\n limit $2;\n";

const appArtifactSql =
  "-- §9.7 AppArtifactSource: kind in ('app','model3d'), ordered by co-install\n-- collaborative filtering over the viewer's viewer_recent_actions install/fork ids.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       'agent' as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.kind in ('app', 'model3d')\n order by\n   -- posts co-installed with what this viewer already installed rank first\n   (select count(*)\n      from public.viewer_recent_actions v\n     where v.viewer_user_id = $1::uuid\n       and v.actions @> jsonb_build_array(jsonb_build_object(\n             'action', 'install_app', 'post_id', p.id::text))) desc,\n   p.published_at desc\n limit $2;\n";

const byAuthorsRecentSql =
  "-- §9.7 CoEngagementSource: recent posts by a caller-resolved creator id set.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.author_user_id = any($1::uuid[])\n   and p.published_at > now() - interval '7 days'\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by p.published_at desc\n limit $3;\n";

const coldStartSeedSql =
  "-- §9.7 ColdStartSeedSource: last 48 h, post_counters.impressions below threshold.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.post_counters pc on pc.post_id = p.id\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.published_at > now() - interval '48 hours'\n   and pc.impressions < $1::int\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by p.published_at desc\n limit $3;\n";

const completionTrendingSql =
  "-- §9.24 CompletionTrendingSource: velocity top-N (caller passes 500) over media\n-- kinds; the SOURCE re-ranks in memory by completion_rate_24h after loading stats.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.post_stats_rolling r on r.post_id = p.id\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.kind = any($1::post_kind[])        -- reels: {video, audio}\n   and p.published_at > now() - interval '7 days'\n order by r.velocity_24h desc, p.published_at desc\n limit $2;\n";

const followGraphSql =
  "-- packages/muse-mixer/src/adapters/postgres/sql/follow_graph.sql\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.author_user_id = any($1::uuid[])       -- followedCreatorIds\n   and p.published_at > now() - interval '48 hours'\n   and p.author_user_id <> $2::uuid             -- exclude self; Thunder does the same\n   and ($3::post_kind[] is null or p.kind = any($3))   -- 'reels' passes {video,audio}\n order by p.published_at desc\n limit $4;\n";

const remixLineageSql =
  "-- §9.7 RemixLineageSource: posts in the same fork tree as artifacts the viewer\n-- engaged with (remix/fork_app actions → roots resolved by the caller, $1).\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.artifacts a0 on a0.post_id = p.id\n where p.status = 'published'\n   and p.deleted_at is null\n   and null::uuid = any($1::uuid[])  -- never matches until M16 restores `a0.remix_root_id`\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by p.published_at desc\n limit $3;\n";

const reverseChronSql =
  "-- §9.7 ReverseChronSource: the MogBook mog-feed keyset port, ordered by\n-- posts_feed_idx (published_at desc, id desc). $1 = viewerId (excludes self),\n-- $2 = kinds filter, $3 = limit. In-network marks are caller-side, so the\n-- followedCreatorIds list never reaches the query — Postgres rejects a\n-- supplied parameter that has no text reference.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n where p.status = 'published'\n   and p.deleted_at is null\n   and ($1::uuid is null or p.author_user_id <> $1)\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by p.published_at desc, p.id desc\n limit $3;\n";

const soundtrackSql =
  "-- §9.24 SoundtrackSource (reels): other posts sharing an assets row the viewer\n-- played through. Play-throughs come from the worker-maintained\n-- viewer_recent_actions projection — never action_events on this path.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.post_assets pa on pa.post_id = p.id\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.author_user_id <> $1::uuid\n   and pa.asset_id in (\n     select distinct pa2.asset_id\n       from public.post_assets pa2\n      where pa2.post_id in (\n        select (a.elem ->> 'post_id')::uuid\n          from public.viewer_recent_actions v\n               cross join lateral jsonb_array_elements(v.actions) as a(elem)\n         where v.viewer_user_id = $1::uuid\n           and a.elem ->> 'action' = 'play_through'\n           and a.elem ? 'post_id'))\n order by p.published_at desc\n limit $2;\n";

const topicSql =
  "-- §9.7 TopicSource: GIN index post_classifications_topics_gin, c.topics && $1.\n-- distinct on post id so a post matching several topics enters once.\nselect distinct on (p.id)\n       p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.post_classifications c on c.content_hash = p.content_hash\n where p.status = 'published'\n   and p.deleted_at is null\n   and c.topics && $1::text[]                           -- followed ∪ inferred ∪ requested\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by p.id, c.quality desc nulls last, p.published_at desc\n limit $3;\n";

const trendingSql =
  "-- §9.7 TrendingSource: post_stats_rolling_velocity_idx (velocity_24h desc), last 7 d.\nselect p.id as post_id, p.content_hash, p.author_user_id,\n       case when p.posted_by_agent_id is null then 'human' else 'agent' end as creator_kind,\n       p.kind,\n       (extract(epoch from p.published_at) * 1000)::double precision as published_at_ms,\n       null::uuid as remix_root_id  -- artifacts.remix_root_id lands at M16 (§11.13); constant NULL until then\n  from public.posts p\n  join public.post_stats_rolling r on r.post_id = p.id\n where p.status = 'published'\n   and p.deleted_at is null\n   and p.published_at > now() - make_interval(hours => $1::int)\n   and ($2::post_kind[] is null or p.kind = any($2))\n order by r.velocity_24h desc, p.published_at desc\n limit $3;\n";

export const SOURCE_SQL: Record<string, string> = {
  agent_authored: agentAuthoredSql,
  app_artifact: appArtifactSql,
  by_authors_recent: byAuthorsRecentSql,
  cold_start_seed: coldStartSeedSql,
  completion_trending: completionTrendingSql,
  follow_graph: followGraphSql,
  remix_lineage: remixLineageSql,
  reverse_chron: reverseChronSql,
  soundtrack: soundtrackSql,
  topic: topicSql,
  trending: trendingSql,
};
