// scripts/gates/manifest.mjs — the data half of the gate runner (§17.12).
//
// Two lists:
//   UNIVERSAL — runs inside EVERY milestone gate; each entry carries an
//     `activeFrom` milestone and prints `SKIP <id> (activeFrom M<n>)` before
//     it. Transcribed from §16.1's table, which is canonical for activeFrom.
//   GATES — each milestone's numbered check list, transcribed from §16.5.
//
// A check's `id` is the `G-`/`M<n>.<k>` form recorded in .gate/M<n>.json.
// A check's `name` (kebab-case) is the ONLY thing `pnpm gate --check <name>`
// accepts (§17.12.2 property 2). No name → not reachable standalone.
//
// `kind` values:
//   "sh"   — a shell command; green iff it exits 0
//   "fn"   — a function in checks.mjs returning { ok, errors }
//   "sql"  — a psql -Atc against $SUPABASE_DB_URL; green iff output === expect
//   "todo" — transcribed as a reminder; not yet implemented. Counts as a
//            failure if reached — an unimplemented gate check is not a pass.
import * as checks from "./checks.mjs";

export const UNIVERSAL = [
  {
    id: "G-BUILD",
    activeFrom: "M1",
    kind: "sh",
    desc: "pnpm -r build succeeds for every package and app",
    run: "pnpm -r build",
  },
  {
    id: "G-TYPES",
    activeFrom: "M1",
    kind: "fn",
    desc: "typecheck clean; wrangler types output committed and diffs empty",
    run: checks.gTypes,
  },
  {
    id: "G-BOUND",
    activeFrom: "M1",
    kind: "fn",
    desc: "every binding a Worker reads exists in its wrangler.jsonc; no orphans either direction",
    run: checks.gBound,
  },
  {
    id: "G-FMT",
    activeFrom: "M1",
    kind: "sh",
    desc: "prettier --check is clean",
    run: "pnpm format",
  },
  {
    id: "G-TEST",
    activeFrom: "M1",
    kind: "sh",
    desc: "vitest, node tier + every project; passWithNoTests is false",
    run: "pnpm vitest run",
  },
  {
    id: "G-CFTEST",
    activeFrom: "M1",
    kind: "sh",
    desc: "workerd tier: the same files under cloudflareTest()",
    run: "pnpm vitest run --project='*-workers' --project=edge --project=mcp --project=worker",
  },
  {
    id: "G-ENV",
    activeFrom: "M1",
    kind: "sh",
    desc: "every env read is in the §3.7 manifest; examples match byte for byte; no secret in a wrangler.jsonc",
    run: "node scripts/check-env-manifest.mjs",
  },
  {
    id: "G-ZOD",
    activeFrom: "M1",
    kind: "fn",
    name: "zod-split",
    desc: "no zod catalog entry, no overrides.zod, no zod in packages/x402; zod 3 and 4 both resolve",
    run: checks.zodSplit,
  },
  {
    id: "G-AGPL",
    activeFrom: "M1",
    kind: "fn",
    name: "agpl",
    desc: "no Postiz source in the bundle",
    run: checks.agplContainment,
  },
  {
    id: "G-LINT",
    activeFrom: "M1",
    kind: "fn",
    desc: "both spine lint rules at error and biting their fixtures",
    run: checks.gLint,
  },
  {
    id: "G-LEGACY",
    activeFrom: "M1",
    kind: "fn",
    name: "legacy-ref",
    desc: "no reference to the legacy Supabase project",
    run: checks.legacyRef,
  },
  {
    id: "G-VERCEL-DEAD",
    activeFrom: "M1",
    kind: "fn",
    name: "vercel-dead",
    desc: "no dead Vercel-era platform read",
    run: checks.vercelDead,
  },
  {
    id: "G-SKIP",
    activeFrom: "M1",
    kind: "fn",
    desc: "no skipped, todo, only or quarantined test",
    run: checks.gSkip,
  },
  {
    id: "G-CFDRY",
    activeFrom: "M1",
    kind: "sh",
    desc: "all three Workers bundle",
    run: "pnpm cf:dry",
  },
  {
    id: "G-SEED",
    activeFrom: "M2",
    kind: "fn",
    name: "seed-hash",
    desc: "two db resets produce the same ordered dump hash, equal to supabase/SEED_HASH",
    run: checks.seedHash,
  },
  {
    id: "G-RLS",
    activeFrom: "M2",
    kind: "sh",
    name: "db:rls-suite",
    desc: "the pgTAP RLS suite",
    run: "pnpm exec supabase test db",
  },
  {
    id: "G-ROLE",
    activeFrom: "M2",
    kind: "fn",
    name: "db:assert-rls",
    desc: "musebook_worker NOBYPASSRLS + FORCE RLS + Worker-plane grants",
    run: checks.dbAssertRls,
  },
  {
    id: "G-DRIFT",
    activeFrom: "M2",
    kind: "fn",
    name: "db-drift",
    desc: "no schema drift",
    run: checks.dbDrift,
  },
  {
    id: "G-BUNDLE",
    activeFrom: "M3",
    kind: "fn",
    name: "edge-bundle",
    desc: "edge bundle guard: no viem / node:fs / node:path / @x402/paywall / MCP SDK",
    run: checks.edgeBundle,
  },
  {
    id: "G-R2-SEAL",
    activeFrom: "M3",
    kind: "fn",
    name: "r2-seal",
    desc: "3 sealed buckets have no public URL (six assertions)",
    run: checks.r2Seal,
    prereq: "H3",
  },
  {
    id: "G-COV",
    activeFrom: "M4",
    kind: "sh",
    desc: "coverage thresholds",
    run: "pnpm vitest run --coverage",
  },
  {
    id: "G-GOLDEN",
    activeFrom: "M5",
    kind: "fn",
    desc: "generated golden barrel matches the 24 .snap files",
    run: checks.gGolden,
  },
  {
    id: "G-EDGE-ROUTES",
    activeFrom: "M6",
    kind: "fn",
    name: "edge-routes",
    desc: "every §6 gated path has a route in apps/edge/wrangler.jsonc",
    run: checks.edgeRoutes,
  },
  {
    id: "G-PROXY",
    activeFrom: "M6",
    kind: "fn",
    name: "proxy-hygiene",
    desc: "no middleware.ts; proxy.ts 404s a request lacking x-musebook-edge, timing-safe; never strips x-mb-*",
    run: checks.proxyHygiene,
  },
  {
    id: "G-FRESH",
    activeFrom: "M6",
    kind: "fn",
    desc: "every grant/quote/settlement/reservation/approval read names HYPERDRIVE_FRESH",
    run: checks.gFresh,
  },
  {
    id: "G-AXE",
    activeFrom: "M7",
    kind: "fn",
    desc: "zero serious/critical axe violations on the seven audited routes, both themes",
    run: checks.gAxe,
  },
  {
    id: "G-FAKE-TX",
    activeFrom: "M8",
    kind: "fn",
    name: "fake-tx",
    desc: "no fabricated transaction hash or settlement id outside a fixture; no `settled` outside packages/x402/src/settle.ts",
    run: checks.fakeTx,
  },
  {
    id: "G-X402-V1",
    activeFrom: "M8",
    kind: "fn",
    desc: "no x402 v1 header or field name",
    run: checks.x402v1,
  },
  {
    id: "G-PLANE-JOIN",
    activeFrom: "M11",
    kind: "fn",
    name: "plane-join",
    desc: "no query joins the telemetry planes",
    run: checks.planeJoin,
  },
  {
    id: "G-ISO",
    activeFrom: "M13",
    kind: "fn",
    desc: "candidate isolation (spine invariant 2), both runners",
    run: checks.gIso,
  },
];

// Each milestone's numbered list, transcribed from §16.5. Entries past M2 are
// filled in as their milestone is executed — the gate for a milestone reads
// only its own list, and a milestone's list is complete before that gate runs.
export const GATES = {
  M0: [
    {
      id: "M0.1",
      kind: "sh",
      desc: "NS delegation live; zone status active",
      run: 'test "$(dig NS musebook.dev +short | sort | tr "\\n" " ")" && curl -sf -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID" | jq -e \'.result.status == "active"\'',
      prereq: "H1",
    },
    {
      id: "M0.2",
      kind: "sh",
      desc: "SSL mode is strict (set before apex)",
      run: 'curl -sf -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/settings/ssl" | jq -e \'.result.value == "strict"\'',
      prereq: "H1",
    },
    {
      id: "M0.3",
      kind: "fn",
      desc: "O6: ssl setting modified_on earlier than apex record created_on",
      run: checks.m0SslOrdering,
      prereq: "H1",
    },
    {
      id: "M0.4",
      kind: "sh",
      desc: "no redirect loop: one 3xx http→https, https non-3xx",
      run: 'test "$(curl -so /dev/null -w "%{http_code}" -L --max-redirs 3 https://musebook.dev/)" -lt 400',
      prereq: "H1",
    },
    {
      id: "M0.5",
      kind: "fn",
      desc: "apex is proxied CNAME to the Vercel project target",
      run: checks.m0ApexRecord,
      prereq: "H1",
    },
    {
      id: "M0.6",
      kind: "fn",
      desc: "origin.musebook.dev exists, DNS-only, no Worker route",
      run: checks.m0OriginHost,
      prereq: "H1",
    },
    {
      id: "M0.7",
      kind: "fn",
      desc: "musebook.dev renew:true at the Vercel registrar",
      run: checks.m0VercelRenew,
    },
    {
      id: "M0.8",
      kind: "sh",
      desc: "OPERATIONS.md documents the cosmetic Invalid Configuration card",
      run: 'grep -q "Invalid Configuration" OPERATIONS.md',
    },
    {
      id: "M0.9",
      kind: "fn",
      desc: "Bot Fight Mode off (fallback: unchallenged robots.txt fetch)",
      run: checks.m0BotFight,
      prereq: "H1",
    },
    {
      id: "M0.10",
      kind: "fn",
      desc: "AI bot presets explicitly Agent=allow, Search=allow",
      run: checks.m0BotPresets,
      prereq: "H1",
    },
    {
      id: "M0.11",
      kind: "fn",
      desc: "pay-per-crawl off + disable-ppc-x402-paths rule exists",
      run: checks.m0Ppc,
      prereq: "H1",
    },
    {
      id: "M0.12",
      kind: "fn",
      desc: "no WAF custom rule blocks bots on musebook.dev/*",
      run: checks.m0Waf,
      prereq: "H1",
    },
    {
      id: "M0.13",
      kind: "fn",
      desc: "exactly one musebook-prod project, org lskgtzehnlfzimkxhwre, PG17, us-east-1, ACTIVE_HEALTHY",
      run: checks.m0SupabaseProject,
    },
    {
      id: "M0.14",
      kind: "fn",
      desc: "legacy project untouched: 248 public base tables, no new migrations",
      run: checks.m0LegacyUntouched,
    },
    {
      id: "M0.15",
      kind: "sql",
      desc: "public schema empty on musebook-prod",
      sql: "select count(*) from information_schema.tables where table_schema = 'public' and table_type = 'BASE TABLE'",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M0.16",
      kind: "fn",
      desc: "5 extensions in 'extensions' schema, pgmq absent",
      run: checks.m0Extensions,
      prereq: "H2",
    },
    {
      id: "M0.17",
      kind: "sql",
      desc: "pg_cron in pg_catalog, not re-created",
      sql: "select extnamespace::regnamespace::text from pg_extension where extname = 'pg_cron'",
      expect: "pg_catalog",
      prereq: "H2",
    },
    {
      id: "M0.18",
      kind: "fn",
      desc: "two Hyperdrive configs, one max_age 60, one caching-disabled",
      run: checks.m0Hyperdrive,
      prereq: "H3",
    },
    {
      id: "M0.19",
      kind: "fn",
      desc: "five buckets; only musebook-public public; postiz-media bound by no wrangler.jsonc",
      run: checks.m0Buckets,
      prereq: "H3",
    },
    {
      id: "M0.20",
      kind: "fn",
      desc: "musebook-uploads lifecycle: abort multipart at 2 days",
      run: checks.m0Lifecycle,
      prereq: "H3",
    },
    {
      id: "M0.21",
      kind: "fn",
      desc: "fourteen queues with §4.13.2 names + retention; uploads object-create → musebook-r2-events",
      run: checks.m0Queues,
      prereq: "H3",
    },
    {
      id: "M0.22",
      kind: "fn",
      desc: "three KV namespaces exist, ids in OPERATIONS.md",
      run: checks.m0Kv,
      prereq: "H3",
    },
    {
      id: "M0.23",
      kind: "sh",
      desc: "both AE dataset names recorded in OPERATIONS.md",
      run: 'grep -q "musebook_telemetry" OPERATIONS.md && grep -q "musebook_paywall" OPERATIONS.md',
    },
    {
      id: "M0.24",
      kind: "fn",
      desc: "OPERATIONS.md holds every live-read value",
      run: checks.m0Operations,
    },
    {
      id: "M0.25",
      kind: "sh",
      desc: "no secret value in OPERATIONS.md",
      run: "! grep -rniE '(service_role|sb_secret|-----BEGIN|0x[0-9a-f]{64}|^CF_API_TOKEN=)' OPERATIONS.md",
    },
  ],

  M1: [
    {
      id: "M1.1",
      kind: "sh",
      desc: "clean-checkout install + build + test",
      run: "pnpm install --frozen-lockfile && pnpm -r build && pnpm -r test",
    },
    { id: "M1.2", kind: "sh", desc: "all three Workers bundle via cf:dry", run: "pnpm cf:dry" },
    {
      id: "M1.3",
      kind: "sh",
      desc: "worker-configuration.d.ts generated, no diff",
      run: "pnpm cf:types && git diff --exit-code 'apps/*/worker-configuration.d.ts'",
    },
    {
      id: "M1.4",
      kind: "fn",
      desc: "no compatibility_flags anywhere; compatibility_date is 2026-09-21 (incl. env.* blocks)",
      run: checks.m1Compat,
    },
    {
      id: "M1.5",
      kind: "fn",
      desc: "global_fetch_strictly_public not enabled",
      run: checks.m1NoStrictPublic,
    },
    {
      id: "M1.6",
      kind: "fn",
      desc: "publish-mode rule bites its fixtures (incl. a simulated apps/edge path)",
      run: checks.m1PublishModeFixture,
    },
    {
      id: "M1.7",
      kind: "fn",
      desc: "mixer rule bites pg and cloudflare:workers fixtures",
      run: checks.m1MixerFixture,
    },
    {
      id: "M1.8",
      kind: "fn",
      desc: "both spine rules at error, not warn",
      run: checks.m1RulesAtError,
    },
    {
      id: "M1.9",
      kind: "fn",
      desc: "bundle guard fails a deliberate @x402/core root-barrel import",
      run: checks.m1BundleGuardBites,
    },
    { id: "M1.10", kind: "fn", desc: "zod split holds (delegates to G-ZOD)", run: checks.zodSplit },
    {
      id: "M1.11",
      kind: "fn",
      desc: "AGPL guard green (delegates to G-AGPL)",
      run: checks.agplContainment,
    },
    {
      id: "M1.12",
      kind: "fn",
      desc: "Next 16 hygiene: no apps/web/middleware.ts; no next.config.* under apps/mcp",
      run: checks.m1NextHygiene,
    },
    {
      id: "M1.13",
      kind: "fn",
      desc: "config.toml pins the new project ref; legacy-ref green incl. tools/.github",
      run: checks.m1SupabaseRef,
    },
    {
      id: "M1.14",
      kind: "fn",
      desc: "exact-version pins for the moving-weekly deps",
      run: checks.m1ExactPins,
    },
    {
      id: "M1.15",
      kind: "fn",
      desc: "catalog pins resolve: typescript 6.0.3 newest <6.1.0, vitest 4.1.11 newest 4.x, wrangler 4.136.1 latest",
      run: checks.m1CatalogPins,
    },
    { id: "M1.16", kind: "fn", desc: "superseded test runner absent", run: checks.m1NoPoolWorkers },
    {
      id: "M1.17",
      kind: "fn",
      desc: "Vercel-era async/runtime surface absent",
      run: checks.m1NoVercelEra,
    },
    { id: "M1.18", kind: "sh", desc: "G-ENV green", run: "node scripts/check-env-manifest.mjs" },
    {
      id: "M1.19",
      kind: "fn",
      desc: "configure-cf.ts --check: zero drift against the live zone",
      run: checks.m1CfDrift,
      prereq: "H1",
    },
    {
      id: "M1.20",
      kind: "fn",
      desc: "the gate runner itself runs and records skips",
      run: checks.m1SelfTest,
    },
  ],

  M2: [
    {
      id: "M2.1",
      kind: "fn",
      desc: "migrations replay from zero, twice",
      run: checks.m2ResetTwice,
      prereq: "H2",
    },
    {
      id: "M2.2",
      kind: "fn",
      desc: "no drift (G-DRIFT)",
      run: checks.dbDrift,
      prereq: "H2",
    },
    {
      id: "M2.3",
      kind: "fn",
      desc: "security advisors: zero findings",
      run: checks.m2AdvisorsSecurity,
      prereq: "H2",
    },
    {
      id: "M2.4",
      kind: "fn",
      desc: "performance advisors: zero auth_rls_initplan",
      run: checks.m2AdvisorsPerf,
      prereq: "H2",
    },
    {
      id: "M2.5",
      kind: "fn",
      desc: "no bare auth.uid() survives",
      run: checks.m2BareAuthUid,
      prereq: "H2",
    },
    {
      id: "M2.6",
      kind: "fn",
      desc: "G-ROLE: role posture + live policy block as musebook_worker",
      run: checks.dbAssertRls,
      prereq: "H2",
    },
    {
      id: "M2.7",
      kind: "sql",
      desc: "action_events: 4 columns NOT NULL, no defaults",
      sql: "select count(*) from information_schema.columns where table_schema = 'public' and table_name = 'action_events' and column_name in ('slate_id','position','weights_version','model_version') and (is_nullable <> 'NO' or column_default is not null)",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.8",
      kind: "sql",
      desc: "hot/cold split: no counter columns on posts",
      sql: "select count(*) from information_schema.columns where table_schema='public' and table_name='posts' and column_name in ('likes_count','views_count','impressions','comments_count')",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.9",
      kind: "fn",
      desc: "job_outbox: unique(kind,dedupe_key) + partial index on state='queued'",
      run: checks.m2Outbox,
      prereq: "H2",
    },
    {
      id: "M2.10",
      kind: "fn",
      desc: "bootstrap dimension rows: weights_version 'none' + model_version 'reverse_chron'",
      run: checks.m2BootstrapDims,
      prereq: "H2",
    },
    {
      id: "M2.11",
      kind: "fn",
      desc: "two-level partitioning: ≥3 partitioned tables; human/agent partitions exist",
      run: checks.m2Partitions,
      prereq: "H2",
    },
    {
      id: "M2.12",
      kind: "sql",
      desc: "no materialized views",
      sql: "select count(*) from pg_matviews",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.13",
      kind: "fn",
      desc: "types generated, not written",
      run: checks.m2TypesGen,
      prereq: "H2",
    },
    {
      id: "M2.14",
      kind: "fn",
      desc: "seed determinism (G-SEED)",
      run: checks.seedHash,
      prereq: "H2",
    },
    {
      id: "M2.15",
      kind: "fn",
      desc: "slugs globally unique (posts_slug_uniq partial; no posts_author_slug_uniq)",
      run: checks.m2Slugs,
      prereq: "H2",
    },
    {
      id: "M2.16",
      kind: "fn",
      desc: "action_kind=23, post_kind=8 closed; no alter-type migrations",
      run: checks.m2Enums,
      prereq: "H2",
    },
    {
      id: "M2.17",
      kind: "fn",
      desc: "license columns ×7 + constraint + creator_publishing_defaults PK",
      run: checks.m2License,
      prereq: "H2",
    },
    {
      id: "M2.18",
      kind: "fn",
      desc: "assets_url_matches_bucket CHECK rejects an r2_paid cdn URL",
      run: checks.m2BucketCheck,
      prereq: "H2",
    },
    {
      id: "M2.19",
      kind: "fn",
      desc: "migration timestamps unique + set equals §16.8's list",
      run: checks.m2MigrationSet,
    },
  ],

  // M3–M19: transcribed from §16.5 at the start of each milestone.
};

export const MILESTONE_TITLES = {
  M0: "Accounts, DNS delegation and resources",
  M1: "Monorepo, toolchain, CI, lint rules, and the gate runner",
  M2: "Schema, RLS, partitions, job_outbox, the musebook_worker role, and the deterministic seed",
  M3: "Identity and actor resolution in the Worker",
  M4: "@musebook/content",
  M5: "@musebook/kernel",
  M6: "musebook-edge read path",
  M7: "Compose, publish, mode picker, media upload",
  M8: "x402 v2 paywall in the Worker, grants, ledger, paid-media gate",
  M9: "musebook-mcp",
  M10: "Postiz sidecar + distributor",
  M11: "Telemetry: AE write path + Postgres rollups",
  M12: "x402 settlement verification + payouts",
  M13: "muse-mixer isolation + replay",
  M14: "Console + agent surface polish",
  M15: "Learned ranker v1.1",
  M16: "Artifacts surface + sandbox",
  M17: "Media pipeline deep",
  M18: "Distribution breadth",
  M19: "Ops hardening",
};
