// scripts/gates/manifest.mjs — the data half of the gate runner (§17.12).
//
// Two lists:
//   UNIVERSAL — runs inside EVERY milestone gate; each entry carries an
//     `activeFrom` milestone and prints `SKIP <id> (activeFrom M<n>)` before
//     it. Transcribed from §16.1's table, which is canonical for activeFrom.
//   GATES — each milestone's numbered check list, transcribed from §16.5.
//
// A check's `id` is the `G-`/`M<n>.<k>` form recorded in .gate/M<n>.json.
// A check's `name` (kebab-case) is the ONLY thing `pnpm gate --check <name>`
// accepts (§17.12.2 property 2). No name → not reachable standalone.
//
// `kind` values:
//   "sh"   — a shell command; green iff it exits 0
//   "fn"   — a function in checks.mjs returning { ok, errors }
//   "sql"  — a psql -Atc against $SUPABASE_DB_URL; green iff output === expect
//   "todo" — transcribed as a reminder; not yet implemented. Counts as a
//            failure if reached — an unimplemented gate check is not a pass.
import * as checks from "./checks.mjs";

export const UNIVERSAL = [
  {
    id: "G-BUILD",
    activeFrom: "M1",
    kind: "sh",
    desc: "pnpm -r build succeeds for every package and app",
    run: "pnpm -r build",
  },
  {
    id: "G-TYPES",
    activeFrom: "M1",
    kind: "fn",
    desc: "typecheck clean; wrangler types output committed and diffs empty",
    run: checks.gTypes,
  },
  {
    id: "G-BOUND",
    activeFrom: "M1",
    kind: "fn",
    desc: "every binding a Worker reads exists in its wrangler.jsonc; no orphans either direction",
    run: checks.gBound,
  },
  {
    id: "G-FMT",
    activeFrom: "M1",
    kind: "sh",
    desc: "prettier --check is clean",
    run: "pnpm format",
  },
  {
    id: "G-TEST",
    activeFrom: "M1",
    kind: "sh",
    desc: "vitest, node tier + every project; passWithNoTests is false",
    run: "pnpm vitest run",
  },
  {
    id: "G-CFTEST",
    activeFrom: "M1",
    kind: "sh",
    desc: "workerd tier: the same files under cloudflareTest()",
    run: "pnpm vitest run --project='*-workers' --project=edge --project=mcp --project=worker",
  },
  {
    id: "G-ENV",
    activeFrom: "M1",
    kind: "sh",
    desc: "every env read is in the §3.7 manifest; examples match byte for byte; no secret in a wrangler.jsonc",
    run: "node scripts/check-env-manifest.mjs",
  },
  {
    id: "G-ZOD",
    activeFrom: "M1",
    kind: "fn",
    name: "zod-split",
    desc: "no zod catalog entry, no overrides.zod, no zod in packages/x402; zod 3 and 4 both resolve",
    run: checks.zodSplit,
  },
  {
    id: "G-AGPL",
    activeFrom: "M1",
    kind: "fn",
    name: "agpl",
    desc: "no Postiz source in the bundle",
    run: checks.agplContainment,
  },
  {
    id: "G-LINT",
    activeFrom: "M1",
    kind: "fn",
    desc: "both spine lint rules at error and biting their fixtures",
    run: checks.gLint,
  },
  {
    id: "G-LEGACY",
    activeFrom: "M1",
    kind: "fn",
    name: "legacy-ref",
    desc: "no reference to the legacy Supabase project",
    run: checks.legacyRef,
  },
  {
    id: "G-VERCEL-DEAD",
    activeFrom: "M1",
    kind: "fn",
    name: "vercel-dead",
    desc: "no dead Vercel-era platform read",
    run: checks.vercelDead,
  },
  {
    id: "G-SKIP",
    activeFrom: "M1",
    kind: "fn",
    desc: "no skipped, todo, only or quarantined test",
    run: checks.gSkip,
  },
  {
    id: "G-CFDRY",
    activeFrom: "M1",
    kind: "sh",
    desc: "all three Workers bundle",
    run: "pnpm cf:dry",
  },
  {
    id: "G-SEED",
    activeFrom: "M2",
    kind: "fn",
    name: "seed-hash",
    desc: "two db resets produce the same ordered dump hash, equal to supabase/SEED_HASH",
    run: checks.seedHash,
  },
  {
    id: "G-RLS",
    activeFrom: "M2",
    kind: "sh",
    name: "db:rls-suite",
    desc: "the pgTAP RLS suite",
    run: "pnpm exec supabase test db",
  },
  {
    id: "G-ROLE",
    activeFrom: "M2",
    kind: "fn",
    name: "db:assert-rls",
    desc: "musebook_worker NOBYPASSRLS + FORCE RLS + Worker-plane grants",
    run: checks.dbAssertRls,
  },
  {
    id: "G-DRIFT",
    activeFrom: "M2",
    kind: "fn",
    name: "db-drift",
    desc: "no schema drift",
    run: checks.dbDrift,
  },
  {
    id: "G-BUNDLE",
    activeFrom: "M3",
    kind: "fn",
    name: "edge-bundle",
    desc: "edge bundle guard: no viem / node:fs / node:path / @x402/paywall / MCP SDK",
    run: checks.edgeBundle,
  },
  {
    id: "G-R2-SEAL",
    activeFrom: "M3",
    kind: "fn",
    name: "r2-seal",
    desc: "3 sealed buckets have no public URL (six assertions)",
    run: checks.r2Seal,
    prereq: "H3",
  },
  {
    id: "G-COV",
    activeFrom: "M4",
    kind: "sh",
    desc: "coverage thresholds",
    run: "pnpm vitest run --coverage",
  },
  {
    id: "G-GOLDEN",
    activeFrom: "M5",
    kind: "fn",
    desc: "generated golden barrel matches the 24 .snap files",
    run: checks.gGolden,
  },
  {
    id: "G-EDGE-ROUTES",
    activeFrom: "M6",
    kind: "fn",
    name: "edge-routes",
    desc: "every §6 gated path has a route in apps/edge/wrangler.jsonc",
    run: checks.edgeRoutes,
  },
  {
    id: "G-PROXY",
    activeFrom: "M6",
    kind: "fn",
    name: "proxy-hygiene",
    desc: "no middleware.ts; proxy.ts 404s a request lacking x-musebook-edge, timing-safe; never strips x-mb-*",
    run: checks.proxyHygiene,
  },
  {
    id: "G-FRESH",
    activeFrom: "M6",
    kind: "fn",
    desc: "every grant/quote/settlement/reservation/approval read names HYPERDRIVE_FRESH",
    run: checks.gFresh,
  },
  {
    id: "G-AXE",
    activeFrom: "M7",
    kind: "fn",
    desc: "zero serious/critical axe violations on the seven audited routes, both themes",
    run: checks.gAxe,
  },
  {
    id: "G-FAKE-TX",
    activeFrom: "M8",
    kind: "fn",
    name: "fake-tx",
    desc: "no fabricated transaction hash or settlement id outside a fixture; no `settled` outside packages/x402/src/settle.ts",
    run: checks.fakeTx,
  },
  {
    id: "G-X402-V1",
    activeFrom: "M8",
    kind: "fn",
    desc: "no x402 v1 header or field name",
    run: checks.x402v1,
  },
  {
    id: "G-PLANE-JOIN",
    activeFrom: "M11",
    kind: "fn",
    name: "plane-join",
    desc: "no query joins the telemetry planes",
    run: checks.planeJoin,
  },
  {
    id: "G-ISO",
    activeFrom: "M13",
    kind: "fn",
    desc: "candidate isolation (spine invariant 2), both runners",
    run: checks.gIso,
  },
];

// Each milestone's numbered list, transcribed from §16.5. Entries past M2 are
// filled in as their milestone is executed — the gate for a milestone reads
// only its own list, and a milestone's list is complete before that gate runs.
export const GATES = {
  M0: [
    {
      id: "M0.1",
      kind: "sh",
      desc: "NS delegation live; zone status active",
      run: 'test "$(dig NS musebook.dev +short | sort | tr "\\n" " ")" && curl -sf -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID" | jq -e \'.result.status == "active"\'',
      prereq: "H1",
    },
    {
      id: "M0.2",
      kind: "sh",
      desc: "SSL mode is strict (set before apex)",
      run: 'curl -sf -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/settings/ssl" | jq -e \'.result.value == "strict"\'',
      prereq: "H1",
    },
    {
      // The Full(strict)-before-apex ordering mattered only to avert the
      // Vercel 308 loop, which M0.4 asserts post-deploy; the ordering is a
      // historical fact that cannot be retro-fitted.
      id: "M0.3",
      supersededBy: "M12",
      kind: "fn",
      desc: "O6: ssl setting modified_on earlier than apex record created_on",
      run: checks.m0SslOrdering,
      prereq: "H1",
    },
    {
      id: "M0.4",
      kind: "fn",
      desc: "no redirect loop: one 3xx http→https, https non-3xx",
      run: checks.m0NoRedirectLoop,
      prereq: "H1",
    },
    {
      id: "M0.5",
      kind: "fn",
      desc: "apex is proxied CNAME to the Vercel project target",
      run: checks.m0ApexRecord,
      prereq: "H1",
    },
    {
      id: "M0.6",
      kind: "fn",
      desc: "origin.musebook.dev exists, DNS-only, no Worker route",
      run: checks.m0OriginHost,
      prereq: "H1",
    },
    {
      id: "M0.7",
      kind: "fn",
      desc: "musebook.dev renew:true at the Vercel registrar",
      run: checks.m0VercelRenew,
    },
    {
      id: "M0.8",
      kind: "sh",
      desc: "OPERATIONS.md documents the cosmetic Invalid Configuration card",
      run: 'grep -q "Invalid Configuration" OPERATIONS.md',
    },
    {
      id: "M0.9",
      kind: "fn",
      desc: "Bot Fight Mode off (fallback: unchallenged robots.txt fetch)",
      run: checks.m0BotFight,
      prereq: "H1",
    },
    {
      id: "M0.10",
      kind: "fn",
      desc: "AI bot presets explicitly Agent=allow, Search=allow",
      run: checks.m0BotPresets,
      prereq: "H1",
    },
    {
      id: "M0.11",
      kind: "fn",
      desc: "pay-per-crawl off + disable-ppc-x402-paths rule exists",
      run: checks.m0Ppc,
      prereq: "H1",
    },
    {
      id: "M0.12",
      kind: "fn",
      desc: "no WAF custom rule blocks bots on musebook.dev/*",
      run: checks.m0Waf,
      prereq: "H1",
    },
    {
      id: "M0.13",
      kind: "fn",
      desc: "exactly one musebook-prod project, org lskgtzehnlfzimkxhwre, PG17, us-east-1, ACTIVE_HEALTHY",
      run: checks.m0SupabaseProject,
    },
    {
      id: "M0.14",
      kind: "fn",
      desc: "legacy project untouched: 248 public base tables, no new migrations",
      run: checks.m0LegacyUntouched,
    },
    {
      id: "M0.15",
      kind: "sql",
      desc: "public schema empty on musebook-prod",
      sql: "select count(*) from information_schema.tables where table_schema = 'public' and table_type = 'BASE TABLE'",
      expect: "0",
      prereq: "H2",
      // The M2 migration lands the public schema — this is an as-of-M0 fact.
      supersededBy: "M2",
    },
    {
      id: "M0.16",
      kind: "fn",
      desc: "5 extensions in 'extensions' schema, pgmq absent",
      run: checks.m0Extensions,
      prereq: "H2",
    },
    {
      id: "M0.17",
      kind: "fn",
      desc: "pg_cron in pg_catalog, not re-created",
      run: checks.m0PgCron,
      prereq: "H2",
    },
    {
      id: "M0.18",
      kind: "fn",
      desc: "two Hyperdrive configs, one max_age 60, one caching-disabled",
      run: checks.m0Hyperdrive,
      prereq: "H3",
    },
    {
      id: "M0.19",
      kind: "fn",
      desc: "five buckets; only musebook-public public; postiz-media bound by no wrangler.jsonc",
      run: checks.m0Buckets,
      prereq: "H3",
    },
    {
      id: "M0.20",
      kind: "fn",
      desc: "musebook-uploads lifecycle: abort multipart at 2 days",
      run: checks.m0Lifecycle,
      prereq: "H3",
    },
    {
      id: "M0.21",
      kind: "fn",
      desc: "fourteen queues with §4.13.2 names + retention; uploads object-create → musebook-r2-events",
      run: checks.m0Queues,
      prereq: "H3",
    },
    {
      id: "M0.22",
      kind: "fn",
      desc: "three KV namespaces exist, ids in OPERATIONS.md",
      run: checks.m0Kv,
      prereq: "H3",
    },
    {
      id: "M0.23",
      kind: "sh",
      desc: "both AE dataset names recorded in OPERATIONS.md",
      run: 'grep -q "musebook_telemetry" OPERATIONS.md && grep -q "musebook_paywall" OPERATIONS.md',
    },
    {
      id: "M0.24",
      kind: "fn",
      desc: "OPERATIONS.md holds every live-read value",
      run: checks.m0Operations,
    },
    {
      id: "M0.25",
      kind: "sh",
      desc: "no secret value in OPERATIONS.md",
      run: "! grep -rniE '(service_role|sb_secret|-----BEGIN|0x[0-9a-f]{64}|^CF_API_TOKEN=)' OPERATIONS.md",
    },
  ],

  M1: [
    {
      id: "M1.1",
      kind: "sh",
      desc: "clean-checkout install + build + test",
      run: "pnpm install --frozen-lockfile && pnpm -r build && pnpm -r test",
    },
    { id: "M1.2", kind: "sh", desc: "all three Workers bundle via cf:dry", run: "pnpm cf:dry" },
    {
      id: "M1.3",
      kind: "sh",
      desc: "worker-configuration.d.ts generated, no diff",
      run: "pnpm cf:types && git diff --exit-code 'apps/*/worker-configuration.d.ts'",
    },
    {
      id: "M1.4",
      kind: "fn",
      desc: "no compatibility_flags anywhere; compatibility_date is 2026-09-21 (incl. env.* blocks)",
      run: checks.m1Compat,
    },
    {
      id: "M1.5",
      kind: "fn",
      desc: "global_fetch_strictly_public not enabled",
      run: checks.m1NoStrictPublic,
    },
    {
      id: "M1.6",
      kind: "fn",
      desc: "publish-mode rule bites its fixtures (incl. a simulated apps/edge path)",
      run: checks.m1PublishModeFixture,
    },
    {
      id: "M1.7",
      kind: "fn",
      desc: "mixer rule bites pg and cloudflare:workers fixtures",
      run: checks.m1MixerFixture,
    },
    {
      id: "M1.8",
      kind: "fn",
      desc: "both spine rules at error, not warn",
      run: checks.m1RulesAtError,
    },
    {
      id: "M1.9",
      kind: "fn",
      desc: "bundle guard fails a deliberate @x402/core root-barrel import",
      run: checks.m1BundleGuardBites,
    },
    { id: "M1.10", kind: "fn", desc: "zod split holds (delegates to G-ZOD)", run: checks.zodSplit },
    {
      id: "M1.11",
      kind: "fn",
      desc: "AGPL guard green (delegates to G-AGPL)",
      run: checks.agplContainment,
    },
    {
      id: "M1.12",
      kind: "fn",
      desc: "Next 16 hygiene: no apps/web/middleware.ts; no next.config.* under apps/mcp",
      run: checks.m1NextHygiene,
    },
    {
      id: "M1.13",
      kind: "fn",
      desc: "config.toml pins the new project ref; legacy-ref green incl. tools/.github",
      run: checks.m1SupabaseRef,
    },
    {
      id: "M1.14",
      kind: "fn",
      desc: "exact-version pins for the moving-weekly deps",
      run: checks.m1ExactPins,
    },
    {
      id: "M1.15",
      kind: "fn",
      desc: "catalog pins resolve: typescript 6.0.3 newest <6.1.0, vitest 4.1.11 newest 4.x, wrangler 4.136.1 latest",
      run: checks.m1CatalogPins,
    },
    { id: "M1.16", kind: "fn", desc: "superseded test runner absent", run: checks.m1NoPoolWorkers },
    {
      id: "M1.17",
      kind: "fn",
      desc: "Vercel-era async/runtime surface absent",
      run: checks.m1NoVercelEra,
    },
    { id: "M1.18", kind: "sh", desc: "G-ENV green", run: "node scripts/check-env-manifest.mjs" },
    {
      id: "M1.19",
      kind: "fn",
      desc: "configure-cf.ts --check: zero drift against the live zone",
      run: checks.m1CfDrift,
      prereq: "H1",
    },
    {
      id: "M1.20",
      kind: "fn",
      desc: "the gate runner itself runs and records skips",
      run: checks.m1SelfTest,
    },
  ],

  M2: [
    {
      id: "M2.1",
      kind: "fn",
      desc: "migrations replay from zero, twice",
      run: checks.m2ResetTwice,
      prereq: "H2",
    },
    {
      id: "M2.2",
      kind: "fn",
      desc: "no drift (G-DRIFT)",
      run: checks.dbDrift,
      prereq: "H2",
    },
    {
      id: "M2.3",
      kind: "fn",
      desc: "security advisors: zero findings",
      run: checks.m2AdvisorsSecurity,
      prereq: "H2",
    },
    {
      id: "M2.4",
      kind: "fn",
      desc: "performance advisors: zero auth_rls_initplan",
      run: checks.m2AdvisorsPerf,
      prereq: "H2",
    },
    {
      id: "M2.5",
      kind: "fn",
      desc: "no bare auth.uid() survives",
      run: checks.m2BareAuthUid,
      prereq: "H2",
    },
    {
      id: "M2.6",
      kind: "fn",
      desc: "G-ROLE: role posture + live policy block as musebook_worker",
      run: checks.dbAssertRls,
      prereq: "H2",
    },
    {
      id: "M2.7",
      kind: "sql",
      desc: "action_events: 4 columns NOT NULL, no defaults",
      sql: "select count(*) from information_schema.columns where table_schema = 'public' and table_name = 'action_events' and column_name in ('slate_id','position','weights_version','model_version') and (is_nullable <> 'NO' or column_default is not null)",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.8",
      kind: "sql",
      desc: "hot/cold split: no counter columns on posts",
      sql: "select count(*) from information_schema.columns where table_schema='public' and table_name='posts' and column_name in ('likes_count','views_count','impressions','comments_count')",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.9",
      kind: "fn",
      desc: "job_outbox: unique(kind,dedupe_key) + partial index on state='queued'",
      run: checks.m2Outbox,
      prereq: "H2",
    },
    {
      id: "M2.10",
      kind: "fn",
      desc: "bootstrap dimension rows: weights_version 'none' + model_version 'reverse_chron'",
      run: checks.m2BootstrapDims,
      prereq: "H2",
    },
    {
      id: "M2.11",
      kind: "fn",
      desc: "two-level partitioning: ≥3 partitioned tables; human/agent partitions exist",
      run: checks.m2Partitions,
      prereq: "H2",
    },
    {
      id: "M2.12",
      kind: "sql",
      desc: "no materialized views",
      sql: "select count(*) from pg_matviews",
      expect: "0",
      prereq: "H2",
    },
    {
      id: "M2.13",
      kind: "fn",
      desc: "types generated, not written",
      run: checks.m2TypesGen,
      prereq: "H2",
    },
    {
      id: "M2.14",
      kind: "fn",
      desc: "seed determinism (G-SEED)",
      run: checks.seedHash,
      prereq: "H2",
    },
    {
      id: "M2.15",
      kind: "fn",
      desc: "slugs globally unique (posts_slug_uniq partial; no posts_author_slug_uniq)",
      run: checks.m2Slugs,
      prereq: "H2",
    },
    {
      id: "M2.16",
      kind: "fn",
      desc: "action_kind=23, post_kind=8 closed; no alter-type migrations",
      run: checks.m2Enums,
      prereq: "H2",
    },
    {
      id: "M2.17",
      kind: "fn",
      desc: "license columns ×7 + constraint + creator_publishing_defaults PK",
      run: checks.m2License,
      prereq: "H2",
    },
    {
      id: "M2.18",
      kind: "fn",
      desc: "assets_url_matches_bucket CHECK rejects an r2_paid cdn URL",
      run: checks.m2BucketCheck,
      prereq: "H2",
    },
    {
      id: "M2.19",
      kind: "fn",
      desc: "migration timestamps unique + set equals §16.8's list",
      run: checks.m2MigrationSet,
    },
  ],

  // §16.5 M3 — Identity and actor resolution in the Worker. Items 14/15 are
  // the universal checks G-BUNDLE and G-R2-SEAL (activeFrom M3 above).
  M3: [
    {
      id: "M3.1",
      kind: "fn",
      desc: "all four actor classes resolve in the Worker from a constructed Request",
      run: checks.m3ActorClasses,
    },
    {
      id: "M3.2",
      kind: "fn",
      desc: "WBA matrix: absent→human; valid→agent; invalid/expired/unknown→401; unreachable dir + no stale<7d→503 Retry-After:30",
      run: checks.m3WbaOutcomes,
    },
    {
      id: "M3.3",
      kind: "fn",
      desc: "call-site overrides asserted: maxAge 300, clockSkew 30, algorithms exactly [ed25519] (RSA-PSS rejected)",
      run: checks.m3WbaOverrides,
    },
    {
      id: "M3.4",
      kind: "fn",
      desc: "SSRF: non-allowlisted Signature-Agent never fetched; body abandoned at 64KB; 2s timeout",
      run: checks.m3Ssrf,
    },
    {
      id: "M3.5",
      kind: "fn",
      desc: "no hand-rolled RFC 9421 (no Signature-Input building in src); ed25519 on pinned compat date, no flags",
      run: checks.m3VendoredVerifier,
    },
    {
      id: "M3.6",
      kind: "fn",
      desc: "verifiedBot/verifiedBotCategory/score recorded as evidence only; no botManagement reads",
      run: checks.m3BotSignalsEvidenceOnly,
    },
    {
      id: "M3.7",
      kind: "fn",
      desc: "verifyPayload union drives login: tampered signature → .valid:false, generateJWT unreachable",
      run: checks.m3SiweUnion,
    },
    {
      id: "M3.8",
      kind: "fn",
      desc: "domain binding negative: example.com payload fails verifyPayload vs musebook.dev",
      run: checks.m3DomainBinding,
    },
    {
      id: "M3.9",
      kind: "fn",
      desc: "delegations has zero token/api_key/secret columns",
      run: checks.m3NoTokenColumns,
      prereq: "H2",
    },
    {
      id: "M3.10",
      kind: "fn",
      desc: "feed:read token → post:write → 403 naming the missing scope",
      run: checks.m3ScopeGate,
    },
    {
      id: "M3.11",
      kind: "fn",
      desc: "no X-Mog-API-Key / x-mog-api-key anywhere in apps or packages",
      run: checks.m3NoMogKey,
    },
    {
      id: "M3.12",
      kind: "fn",
      desc: "mint + revoke each append exactly one audit_log row (live DB integration)",
      run: checks.m3AuditWrites,
      prereq: "H2",
    },
    {
      id: "M3.13",
      kind: "fn",
      desc: "no resolvePrincipal; exactly one `export const actorSchema` in packages/schema/src",
      run: checks.m3ActorShape,
    },
  ],

  // §16.5 M4 — @musebook/content. G-COV activates at M4 (universal, above).
  M4: [
    {
      id: "M4.1",
      kind: "fn",
      desc: "property test: ≥1,000 whitespace-equivalent inputs (trailing spaces, CRLF vs LF, trailing newline, nested-list indentation) → identical content_hash",
      run: checks.m4HashStability,
    },
    {
      id: "M4.2",
      kind: "fn",
      desc: "one-character body change produces a different hash",
      run: checks.m4HashSensitivity,
    },
    {
      id: "M4.3",
      kind: "fn",
      desc: "all six representations produced for a fixture: 'html'|'markdown'|'json'|'jsonld'|'mcp'|'feed'",
      run: checks.m4SixReps,
    },
    {
      id: "M4.4",
      kind: "fn",
      desc: 'etag.test.ts pins W/"sha256-<16 lowercase hex>-<as>"; differs per representation',
      run: checks.m4EtagPin,
    },
    {
      id: "M4.5",
      kind: "fn",
      desc: "the suite passes under BOTH plain vitest AND @cloudflare/vitest-plugin with identical hashes",
      run: checks.m4DualRunner,
    },
    {
      id: "M4.6",
      kind: "fn",
      desc: "no app attached: grep finds no '@musebook/content' under apps/",
      run: checks.m4NoAppImport,
      supersededBy: "M6", // edge legitimately consumes @musebook/content from M6
    },
  ],

  M5: [
    {
      id: "M5.1",
      kind: "fn",
      desc: "all 24 golden fixtures pass (3 modes x 2 actors x 4 reps), byte-identical under node and workerd",
      run: checks.m5GoldenFixtures,
    },
    {
      id: "M5.2",
      kind: "fn",
      desc: "SECRET_MARKER: no denied body contains MUSEBOOK_PAID_BODY_MARKER_7f3a",
      run: checks.m5SecretMarker,
    },
    {
      id: "M5.3",
      kind: "fn",
      desc: "jsonld: 6 assertions on isAccessibleForFree/hasPart; feed: 3 on content_text === summary",
      run: checks.m5JsonldFeed,
    },
    {
      id: "M5.4",
      kind: "fn",
      desc: "fail-closed: throwing GrantPort AND PaymentPort each produce allow:false + zero-length body",
      run: checks.m5FailClosed,
    },
    {
      id: "M5.5",
      kind: "fn",
      desc: "preview determinism: 1,000 generated bodies byte-identical; never splits a fenced code block",
      run: checks.m5PreviewDeterminism,
    },
    {
      id: "M5.6",
      kind: "fn",
      desc: "cache posture: decision.cache.shared === false for every non-'free' allow reason; no CDN-Cache-Control",
      run: checks.m5CachePosture,
    },
    {
      id: "M5.7",
      kind: "fn",
      desc: "purity: index callable with stub ports in plain Node; no cloudflare:/pg/@cloudflare imports under packages/kernel/src",
      run: checks.m5Purity,
    },
    {
      id: "M5.8",
      kind: "fn",
      desc: "containment: publish_mode|publishMode only under packages/kernel/ + the two named schema files (file by file)",
      run: checks.m5Containment,
    },
    {
      id: "M5.9",
      kind: "fn",
      desc: "no app attached: grep finds no '@musebook/kernel' under apps/",
      run: checks.m5NoAppImport,
      supersededBy: "M6", // edge wraps @musebook/kernel from M6
    },
    {
      id: "M5.10",
      kind: "fn",
      desc: 'ETag W/"sha256-<16hex>-<as>" per rep, six distinct, produced only in packages/kernel/src/headers.ts',
      run: checks.m5EtagSingleProducer,
    },
    {
      id: "M5.11",
      kind: "fn",
      desc: "mintsDurableGrant: true only for human_free_agent_paid",
      run: checks.m5MintsDurableGrant,
    },
  ],

  // §16.5 M6 — musebook-edge read path. Item 2 is the universal G-PROXY
  // (activeFrom M6 above); item 32 is the G-FAKE-TX skip (activeFrom M8).
  M6: [
    {
      id: "M6.1",
      kind: "fn",
      desc: "Worker in the path + origin closed: proxy.ts 404s no/wrong x-musebook-edge",
      run: checks.m6WorkerInPath,
    },
    // M6.2 — G-PROXY (universal): proxy-hygiene runs from this milestone on.
    {
      id: "M6.3",
      kind: "fn",
      desc: "twin byte-consistency on the wire: one hash, per-rep ETags, If-None-Match 304, Accept: text/markdown",
      run: checks.m6TwinWire,
    },
    {
      id: "M6.4",
      kind: "fn",
      desc: "twins worker-served only; ! test -e apps/web/app/api/twin",
      run: checks.m6TwinsWorkerOnly,
    },
    {
      id: "M6.5",
      kind: "fn",
      desc: "O3: zero action_events with null slate_id/position/weights_version/model_version",
      run: checks.m6EventPositions,
    },
    {
      id: "M6.6",
      kind: "fn",
      desc: "O3: all stored weights_version='none'/model_version='reverse_chron'; forged values still store 'none'",
      run: checks.m6BootstrapLiterals,
    },
    {
      id: "M6.7",
      kind: "fn",
      desc: "O3: every viewer-owned slate has action_events coverage (anon slates are AE-only by design)",
      run: checks.m6SlateCoverage,
    },
    {
      id: "M6.8",
      kind: "fn",
      desc: "O3: impression positions dense and zero-based per slate (no gaps, no dups)",
      run: checks.m6PositionDensity,
    },
    {
      id: "M6.9",
      kind: "fn",
      desc: "request path reads not scores: no muse-mixer import, no direct slates select, page-2 same slate",
      run: checks.m6ReadNotScore,
    },
    {
      id: "M6.10",
      kind: "fn",
      desc: "slate writes only under apps/worker/src (insert into public.slates)",
      run: checks.m6SlateWriterPlacement,
    },
    {
      id: "M6.11",
      kind: "fn",
      desc: "inbound x-mb-* never reaches the origin; x-mb-request-id minted by the Worker",
      run: checks.m6ForgedTrustHeaders,
    },
    {
      id: "M6.12",
      kind: "fn",
      desc: "x-mb-country = request.cf.country ?? 'XX'; no Vercel-era geo/IP helpers",
      run: checks.m6GeoFromCf,
    },
    {
      id: "M6.13",
      kind: "fn",
      desc: "DNT:1 writes zero action_events AND zero AE points; post_counters.impressions +1",
      run: checks.m6DntOptOut,
    },
    {
      id: "M6.14",
      kind: "fn",
      desc: "CF-Connecting-IP read in exactly apps/edge/src/index.ts + telemetry/privacy.ts",
      run: checks.m6ClientIpScope,
    },
    {
      id: "M6.15",
      kind: "fn",
      desc: "outbox write is one statement: no BEGIN; enqueue.ts calls app.enqueue_job",
      run: checks.m6OneStatementOutbox,
    },
    {
      id: "M6.16",
      kind: "fn",
      desc: "sweeper recovers a dropped enqueue: queued row becomes running/succeeded within ~60s",
      run: checks.m6SweeperRecovery,
    },
    {
      id: "M6.17",
      kind: "fn",
      desc: "DLQ consumer acts: job_outbox state='dead' + ops_events error on a poisoned message",
      run: checks.m6DlqConsumed,
    },
    {
      id: "M6.18",
      kind: "fn",
      desc: "consumers idempotent: same message twice = one side effect, keyed on dedupe_key",
      run: checks.m6IdempotentConsumers,
    },
    {
      id: "M6.19",
      kind: "fn",
      desc: "messages serialize under 128 KB and carry only ids/R2 keys",
      run: checks.m6MessageSize,
    },
    {
      id: "M6.20",
      kind: "fn",
      desc: "cdn.musebook.dev: Cache Everything + edge_ttl rule present, Smart Tiered on — Worker-free path",
      run: checks.m6CdnCacheEverything,
    },
    {
      id: "M6.21",
      kind: "fn",
      desc: "paid media only through the Worker: 402 no-grant zero bytes; 200 with grant; bucket sealed",
      run: checks.m6PaidMediaGate,
    },
    {
      id: "M6.22",
      kind: "fn",
      desc: "no presigned URL on a read path: ! grep aws4|X-Amz-Signature|presign in media.ts/routes",
      run: checks.m6NoPresignReads,
    },
    {
      id: "M6.23",
      kind: "fn",
      desc: "Range: 206 + Content-Range from R2Object.size; unsatisfiable precondition → 412 no body",
      run: checks.m6RangeCorrectness,
    },
    {
      id: "M6.24",
      kind: "fn",
      desc: "reels: surface='reels' slate serves; play/play_through land in Postgres AND AE",
      run: checks.m6ReelsEvents,
    },
    {
      id: "M6.25",
      kind: "fn",
      desc: "O9 telemetry split: every event in AE; label sample in Postgres; impression per §13.1.1",
      run: checks.m6TelemetrySplit,
    },
    {
      id: "M6.26",
      kind: "fn",
      desc: "AE holds no subjects: Point contract @ts-expect-error + one writeDataPoint site (ae.ts)",
      run: checks.m6AeNoSubjects,
    },
    {
      id: "M6.27",
      kind: "fn",
      desc: "firehose never through Queues: no Q_TELEMETRY/queue impression in apps/edge/src",
      run: checks.m6NoTelemetryQueue,
    },
    {
      id: "M6.28",
      kind: "fn",
      desc: "/_next/static/* not routed through the Worker (wrangler routes); G-EDGE-ROUTES superset",
      run: checks.m6StaticNotRouted,
    },
    {
      id: "M6.29",
      kind: "fn",
      desc: "/_next/image + /_vercel/image cached: rule with cache:true + deception armor; polish/mirage off",
      run: checks.m6NextImageCached,
    },
    {
      id: "M6.30",
      kind: "fn",
      desc: "vendor-prefixed cache headers only — never bare CDN-Cache-Control; no override_origin on gated paths",
      run: checks.m6NoDoubleCache,
    },
    {
      id: "M6.31",
      kind: "fn",
      desc: "no paid body in any crawl surface; §6.12.8's 7 always-free paths reachable via the two lists",
      run: checks.m6CrawlNoPaidBytes,
    },
    {
      id: "M6.32",
      kind: "fn",
      desc: "G-FAKE-TX activeFrom is M8 — prints SKIP at M6",
      run: checks.m6FakeTxSkipped,
    },
  ],

  // §16.5 M7 — compose, publish, mode picker, media upload. Item 10 runs the
  // universal G-AXE sweep for the first time (its activeFrom flips to M7).
  M7: [
    {
      id: "M7.1",
      kind: "fn",
      desc: "sign-in → compose (one video post w/ real media upload) → publish ×3 modes → render /p/{slug} via Worker",
      run: checks.m7PublishThreeModes,
    },
    {
      id: "M7.2",
      kind: "fn",
      desc: "presigned PUT lands in musebook-uploads only; foreign bucket 400; aws4fetch grep = uploads.ts alone",
      run: checks.m7PresignScope,
    },
    {
      id: "M7.3",
      kind: "fn",
      desc: "X-Amz-Expires=900; expired replay → 403 ExpiredRequest with no CORS headers",
      run: checks.m7PresignTtl,
    },
    {
      id: "M7.4",
      kind: "fn",
      desc: "Toll sentence grep under apps/web/app/(app)/compose — 'a declared contract, not a detection guarantee'",
      run: checks.m7TollSentence,
    },
    {
      id: "M7.5",
      kind: "fn",
      desc: "publish is one statement: 2 queued classify+embed rows; M6.15 BEGIN-grep re-run",
      run: checks.m7PublishOneStatement,
    },
    {
      id: "M7.6",
      kind: "fn",
      desc: "globally unique slugs on the wire (same title → distinct slugs); M2.15 re-run",
      run: checks.m7SlugUniqueness,
    },
    {
      id: "M7.7",
      kind: "fn",
      desc: "edit-after-grant warning rendered on the composer (Playwright substring)",
      run: checks.m7EditGrantWarning,
    },
    {
      id: "M7.8",
      kind: "fn",
      desc: "upload→event→consumer: staging object gone, one assets row matching the CHECK; queue producer bound",
      run: checks.m7UploadPromotion,
    },
    {
      id: "M7.9",
      kind: "fn",
      desc: "lifecycle: abort-incomplete-multipart 2d AND staging/ expire 7d on musebook-uploads",
      run: checks.m7StagingLifecycle,
    },
    {
      id: "M7.10",
      kind: "fn",
      desc: "G-AXE green: zero serious/critical violations, 7 routes × light+dark, /reels included",
      run: checks.m7Axe,
    },
    {
      id: "M7.11",
      kind: "fn",
      desc: "§14 M7 rows: JS-off gated body vs Worker; no Testimonials/MotionBackground; no repeat:Infinity/animate-pulse/hex; reduced-motion reels",
      run: checks.m7Section14Acceptance,
    },
    {
      id: "M7.12",
      kind: "fn",
      desc: "browser never names musebook-paid/-artifacts/-logs (apps/web + packages/ui grep)",
      run: checks.m7BucketNaming,
    },
  ],

  // §16.5 M8 — x402 v2 paywall in the Worker, grants, ledger, paid-media gate.
  // The wire tier (m8-wire) settles real testnet USDC through the x402.org
  // facilitator; the DB tier (m8-x402) proves the nonce claim at SQL level.
  M8: [
    {
      id: "M8.1",
      kind: "fn",
      desc: "testnet round trip: 402 names X402_PAY_TO + X402_NETWORK, Base Sepolia pay, replay → 200 body",
      run: checks.m8RoundTrip,
    },
    {
      id: "M8.2",
      kind: "fn",
      desc: "100-way replay of one signed authorization → exactly 1 x402_settlements row, no second settle",
      run: checks.m8OneSettlement,
    },
    {
      id: "M8.3",
      kind: "fn",
      desc: "G-FRESH green and it bites: a deliberate CACHED grant-read fixture turns it red",
      run: checks.m8FreshBites,
    },
    {
      id: "M8.4",
      kind: "fn",
      desc: "KV caches positives only: no deny/false/null GRANTS.put; miss falls through to Postgres",
      run: checks.m8KvPositivesOnly,
    },
    {
      id: "M8.5",
      kind: "fn",
      desc: "mintsDurableGrant honest on the wire: settled hfap → content_hash grant; x402_always → none",
      run: checks.m8DurableGrantHonest,
    },
    {
      id: "M8.6",
      kind: "fn",
      desc: "paid-media gate: no grant → 402 + zero bytes; grant → 200; G-R2-SEAL over all buckets",
      run: checks.m8PaidMediaGate,
    },
    {
      id: "M8.7",
      kind: "fn",
      desc: "EIP-712 domain on target net: assert-asset-domain exits 0; wrong-domain sign → facilitator invalid_exact_evm",
      run: checks.m8AssetDomain,
    },
    {
      id: "M8.8",
      kind: "fn",
      desc: "no settlement key / EIP-712 recovery at the edge (hashTypedData|recoverTypedDataAddress|createPublicClient) + G-BUNDLE",
      run: checks.m8NoEdgeRecovery,
    },
    {
      id: "M8.11",
      kind: "fn",
      desc: "ledger carries policy version: no null revenue_share_version on settlements/posts; no platform_fee_bps in edge src",
      run: checks.m8PolicyVersioned,
    },
    {
      id: "M8.12",
      kind: "fn",
      desc: "mainnet fallback as config: OPERATIONS.md records prod X402_MODE + date + /supported evidence; wrangler agrees",
      run: checks.m8MainnetModeRecorded,
    },
  ],
  // §16.5 M9 — musebook-mcp: remote MCP Worker (MCP 2026-07-28), OAuth 2.1 +
  // RFC 9728 PRM, x402-over-MCP, connector registry, scheduled drafting, the
  // Q_AGENT_CANCEL pipeline, musebook.dev/mcp routing, and the musebook CLI.
  // JWKS is superseded by plan line 8356 — PRM only (deviation logged).
  M9: [
    {
      id: "M9.1",
      kind: "fn",
      desc: "§7.20 owned checks as test files: discover envelope, deterministic ≤11 tools, resultType, spec-exact 402, _meta carrier, robots Content-Usage, feeds leak nothing, stored license on the deny, WebMCP no-op spec",
      run: checks.m9WireChecks,
    },
    {
      id: "M9.2",
      kind: "fn",
      desc: "RFC 9728 protected-resource metadata served by the OAuthProvider (JWKS superseded — plan line 8356, deviation logged)",
      run: checks.m9ProtectedResource,
    },
    {
      id: "M9.3",
      kind: "fn",
      desc: "Host/Origin validated: foreign Origin + bad Host rejected on the wire, allowedHostnames in source",
      run: checks.m9HostOrigin,
    },
    {
      id: "M9.4",
      kind: "fn",
      desc: "forbidden packages stay forbidden; no durable_objects/migrations in apps/mcp/wrangler.jsonc; no compatibility_flags in any wrangler",
      run: checks.m9Forbidden,
    },
    {
      id: "M9.5",
      kind: "fn",
      desc: "zod split survives dual install: musebook-mcp direct 4.6.5, a 3.x line coexists via @x402/core",
      run: checks.m9ZodSplit,
    },
    {
      id: "M9.6",
      kind: "fn",
      desc: "manual schedule → 1 pending_approval post + 1 settled reservation (drainDueSchedules)",
      run: checks.m9AgentDraft,
    },
    {
      id: "M9.7",
      kind: "fn",
      desc: "two-phase hold is real: stale hold swept, cap restored, re-settle reports reservation_settled without double-commit",
      run: checks.m9TwoPhaseHold,
    },
    {
      id: "M9.8",
      kind: "fn",
      desc: "all 4 transports pass packages/connectors/test/contract/all.test.ts",
      run: checks.m9ConnectorContract,
    },
    {
      id: "M9.9",
      kind: "fn",
      desc: "Q_AGENT_CANCEL exists/bound/consumed: revoked delegation → 1 outbox intent → consumer drains it",
      run: checks.m9CancelQueue,
    },
    {
      id: "M9.10",
      kind: "fn",
      desc: "scope enforcement + audit trail: feed:read on submit_post names post:write; revoke appends exactly 1 audit row",
      run: checks.m9ScopeAudit,
    },
    {
      id: "M9.11",
      kind: "fn",
      desc: "no token/api_key/secret columns on delegations or connector_credentials",
      run: checks.m9NoSecretColumns,
    },
    {
      id: "M9.12",
      kind: "fn",
      desc: "G-ENV covers the third Worker: MCP secret names in the manifest, absent from wrangler vars",
      run: checks.m9EnvManifest,
    },
    {
      id: "M9.13",
      kind: "fn",
      desc: "§7.20 static greps 17/19/20/26: no navigator.modelContext, no publish-mode reads outside kernel, one x402 impl + maxTimeoutSeconds=60, no presigned URLs outside upload",
      run: checks.m9StaticChecks,
    },
    {
      id: "M9.14",
      kind: "fn",
      desc: "startup budget: wrangler check startup < 400ms (hyperdrive bindings stripped for local profiling)",
      run: checks.m9StartupBudget,
    },
  ],

  // §16.5 M10 — @musebook/distributor + the Postiz sidecar: full-port variants,
  // one-bucket Postiz call, AGPL containment, seeded constraints, the fan-out
  // review surface, and the sidecar's own R2 domain.
  M10: [
    {
      id: "M10.1",
      kind: "fn",
      desc: "one POST /public/v1/posts per 3-channel fan-out (acceptance 8)",
      run: checks.m10SinglePostizCall,
    },
    {
      id: "M10.2",
      kind: "fn",
      desc: "G-AGPL clean and infra/postiz/Dockerfile exists (FROM-only pin)",
      run: checks.m10AgplDockerfile,
    },
    {
      id: "M10.3",
      kind: "fn",
      desc: "13 platforms seeded; none unverified or null limits_source",
      run: checks.m10PlatformSeed,
    },
    {
      id: "M10.4",
      kind: "fn",
      desc: "countEffective↔validator parity property for all 13 platforms",
      run: checks.m10CounterParity,
    },
    {
      id: "M10.5",
      kind: "fn",
      desc: "media.public_origin is a hard error (paid URL fails, cdn passes)",
      run: checks.m10PublicOrigin,
    },
    {
      id: "M10.6",
      kind: "fn",
      desc: "variants are full ports, not teasers (CF-SPINE §13.3)",
      run: checks.m10FullPorts,
    },
    {
      id: "M10.7",
      kind: "fn",
      desc: "every DistributionMessage <128KB and carries ids/R2 keys only",
      run: checks.m10MessageTransport,
    },
    {
      id: "M10.8",
      kind: "fn",
      desc: "consumer idempotent: same send twice = one Postiz call",
      run: checks.m10IdempotentConsumer,
    },
    {
      id: "M10.9",
      kind: "fn",
      desc: "unconnected channel is a loud error, not a silent no-op",
      run: checks.m10UnconnectedChannel,
    },
    {
      id: "M10.10",
      kind: "fn",
      desc: "licence inheritance: creator_publishing_defaults CC0-1.0+train_ai carried to new posts",
      run: checks.m10LicenseInheritance,
    },
    {
      id: "M10.11",
      kind: "fn",
      desc: "action_events_daily re-keyed (day, actor_plane, source, post_id, action), totals preserved",
      run: checks.m10RekeyedDaily,
    },
    {
      id: "M10.12",
      kind: "fn",
      desc: "musebook-postiz-media serves media.postiz.musebook.dev; no Worker binds it",
      run: checks.m10SidecarBucket,
    },
  ],

  // §16.6 M11 — telemetry rollups, the ops plane, consent + DSAR, alerting,
  // and cost controls.
  M11: [
    {
      id: "M11.1",
      kind: "fn",
      desc: "all 22 §13.11 acceptance checks green",
      run: checks.m11Acceptance,
    },
    {
      id: "M11.2",
      kind: "fn",
      desc: "28 alert_rules seeded+enabled; evaluator fires on an injected fault",
      run: checks.m11AlertRules,
    },
    {
      id: "M11.3",
      kind: "fn",
      desc: "evaluators watch each other (edge-alert-pass ↔ evaluate-alerts)",
      run: checks.m11CrossWatch,
    },
    {
      id: "M11.4",
      kind: "fn",
      desc: "G-PLANE-JOIN: no serve path joins telemetry to identity",
      run: checks.m11PlaneJoin,
    },
    {
      id: "M11.5",
      kind: "fn",
      desc: "Logpush→musebook-logs/workers/{DATE}, logpush:true ×3, 30d lifecycle, no 'log drain'",
      run: checks.m11Logpush,
    },
    {
      id: "M11.6",
      kind: "fn",
      desc: "retention refuses to drop an unsummarized partition",
      run: checks.m11RetentionRefusal,
    },
    {
      id: "M11.7",
      kind: "fn",
      desc: "DLQ drill covers every producer -dlq queue",
      run: checks.m11DlqCoverage,
    },
    {
      id: "M11.8",
      kind: "fn",
      desc: "outbox drill: failed send → queued → sweeper drains",
      run: checks.m11OutboxDrill,
    },
    {
      id: "M11.9",
      kind: "fn",
      desc: "DSAR round-trip wired; dsar/ carries a 7-day expiry on musebook-paid",
      run: checks.m11Dsar,
    },
    {
      id: "M11.10",
      kind: "fn",
      desc: "rollup tables unreachable outside app.creator_dashboard",
      run: checks.m11RollupIsolation,
    },
    {
      id: "M11.11",
      kind: "fn",
      desc: "third lint rule (no-action-events-at-serve-time) live at error",
      run: checks.m11ThirdLintRule,
    },
    {
      id: "M11.12",
      kind: "fn",
      desc: "cost controls as account state (killswitch, budgets, rate limit, spend)",
      run: checks.m11CostControls,
    },
    {
      id: "M11.13",
      kind: "fn",
      desc: "worker route-less, cron triggers carry no shared-secret header",
      run: checks.m11WorkerRouteless,
    },
  ],

  // §16.6 M12 — launch hardening: every §17 gate asserted at once, against
  // production, plus the four silent-death API reads.
  M12: [
    {
      id: "M12.1",
      kind: "fn",
      desc: "every §17 gate green against production (incl. T5 live tier)",
      run: checks.m12AllGatesGreen,
    },
    {
      id: "M12.2",
      kind: "fn",
      desc: "one real mainnet settlement (tx + revenue_share_version + facilitator_url)",
      run: checks.m12MainnetSettlement,
    },
    {
      id: "M12.3",
      kind: "fn",
      desc: "facilitator /supported lists X402_NETWORK at x402Version 2",
      run: checks.m12FacilitatorSupported,
    },
    {
      id: "M12.4",
      kind: "fn",
      desc: "synthetic 402 live + fired + failure-path drilled",
      run: checks.m12Synthetic402,
    },
    {
      id: "M12.5",
      kind: "fn",
      desc: "nightly suite exists and is green twice consecutively",
      run: checks.m12NightlyGreen,
    },
    {
      id: "M12.6",
      kind: "fn",
      desc: "no preview holds a production route; preview unindexed",
      run: checks.m12PreviewIsolation,
    },
    {
      id: "M12.7",
      kind: "fn",
      desc: "origin still closed + PREVIOUS-first rotation drill recorded",
      run: checks.m12OriginClosed,
    },
    {
      id: "M12.8",
      kind: "fn",
      desc: "sealed buckets still sealed; cdn the only custom domain",
      run: checks.m12R2Seal,
    },
    {
      id: "M12.9",
      kind: "fn",
      desc: "kill-switch drill recorded with elapsed time",
      run: checks.m12KillSwitchDrill,
    },
    {
      id: "M12.10",
      kind: "fn",
      desc: "renew:true, zone active, NS pair, SSL strict — live API reads",
      run: checks.m12ZoneHealth,
    },
    {
      id: "M12.11",
      kind: "fn",
      desc: "no universal check skipping — every activeFrom ≤ M12 but G-ISO",
      run: checks.m12NoUniversalSkipping,
    },
    {
      id: "M12.12",
      kind: "fn",
      desc: "launch copy honest — both prices, Toll sentence, P2 as logged slate",
      run: checks.m12LaunchCopy,
    },
  ],
  M13: [
    {
      id: "M13.1",
      kind: "fn",
      desc: "G-ISO bit-identical alone AND in a batch of 200 under BOTH vitest tiers; isolation-bites proves the detector fails on a contaminated scorer",
      run: checks.m13Iso,
    },
    {
      id: "M13.2",
      kind: "fn",
      desc: "zero platform imports outside adapters/ in packages/muse-mixer/src (pg/postgres/next/cloudflare/onnxruntime/env.*) + M5 gate 7 grep re-run",
      run: checks.m13NoPlatformImports,
    },
    {
      id: "M13.3",
      kind: "fn",
      desc: "request path reads not scores (M6.9 re-run): no muse-mixer import in apps/edge, exactly one read_slate_doc call site, app.read_slate EXECUTE kernel+jobs only",
      run: checks.m13ReadNotScore,
    },
    {
      id: "M13.4",
      kind: "fn",
      desc: "feed p95 unchanged vs M12 baseline in OPERATIONS.md — local read_slate_doc p95 measured and recorded",
      run: checks.m13FeedP95,
    },
    {
      id: "M13.5",
      kind: "fn",
      desc: "post_embeddings == distinct published content_hashes, vector 1536-dim, retrieve_similar_posts rows; truncated user_embeddings → full slate + muse.stage.disabled",
      run: checks.m13Embeddings,
    },
    {
      id: "M13.6",
      kind: "fn",
      desc: "exactly two new tables (creator_clusters, viewer_seen_bloom); model_registry_status_allowed still candidate|shadow|active|retired",
      run: checks.m13Schema,
    },
    {
      id: "M13.7",
      kind: "fn",
      desc: "three-score discipline + runtime weights: ranking_weights update changes loaded weights with no deploy; seeded viewer home+reels slates candidate_count > 0",
      run: checks.m13RuntimeWeights,
    },
    {
      id: "M13.8",
      kind: "fn",
      desc: "every served item carries position — M6 gates 5–8 re-run (positions, literals, coverage, density)",
      run: checks.m13PositionDiscipline,
    },
  ],
  M14: [
    {
      id: "M14.1",
      kind: "fn",
      desc: "battery returns for every published seed post — non-null taxonomy_leaf, medium, audience_level, agent_value (live Jev; BLOCKs without TYPESAFE_API_KEY)",
      run: checks.m14BatteryLive,
    },
    {
      id: "M14.2",
      kind: "fn",
      desc: "a post publishes when Jev is down — job deferred, never skipped (ops_events provider_5xx + outbox retry)",
      run: checks.m14PublishWhenJevDown,
    },
    {
      id: "M14.3",
      kind: "fn",
      desc: "client constructed lazily — no module-scope new TypeSafeClient; only makeClient in client.ts",
      run: checks.m14LazyClient,
    },
    {
      id: "M14.4",
      kind: "fn",
      desc: "Jev classifies only, never generates — no 'typesafe' in media/distributor/web, @typesafe-ai/sdk only in packages/classify",
      run: checks.m14JevOnlyClassifies,
    },
    {
      id: "M14.5",
      kind: "fn",
      desc: "no q_ prefix survives — columns are audience_level and agent_value (verbatim grep)",
      run: checks.m14NoQPrefix,
    },
    {
      id: "M14.6",
      kind: "fn",
      desc: "version settings set, not defaulted — classify_versions row matches package constants; every typesafe_jev row carries both stamps",
      run: checks.m14VersionsSet,
    },
    {
      id: "M14.7",
      kind: "fn",
      desc: "token budget bites — over-budget defers w/ ops_events + degraded counter; A14 classify.degraded rule fires",
      run: checks.m14TokenBudget,
    },
    {
      id: "M14.8",
      kind: "fn",
      desc: "G-DRIFT + G-ROLE cover the new columns — replay from zero, RLS forced, Worker-plane grants, §8.7 columns exist",
      run: checks.m14DriftRole,
    },
  ],
  M15: [
    {
      id: "M15.1",
      kind: "fn",
      desc: "§9.15 five-part promotion query returns all true, 30-day window — honest BLOCK on a dev corpus below the floor",
      run: checks.m15EventCountTrigger,
    },
    {
      id: "M15.2",
      kind: "fn",
      desc: "shadow week: shadow ranker resolves, dual-score muse.shadow_score point per scored slate, flip = registry status change — 7-day window BLOCKs (wall-clock)",
      run: checks.m15ShadowWeek,
    },
    {
      id: "M15.3",
      kind: "fn",
      desc: "flip reversible in one statement — registry status UPDATEs flip and flip back, served ranker changes both times",
      run: checks.m15FlipReversible,
    },
    {
      id: "M15.4",
      kind: "fn",
      desc: "attribution: every slates row carries non-null weights_version + model_version of the ranker that produced it",
      run: checks.m15VersionAttribution,
    },
    {
      id: "M15.5",
      kind: "fn",
      desc: "G-ISO still green non-trivially — LearnedMuseRanker registered as a covered stage, isolation + isolation-bites green both tiers",
      run: checks.m15Isolation,
    },
    {
      id: "M15.6",
      kind: "fn",
      desc: "reels scorer is its own scorer — own source set + surface-gated WatchTimeScorer; one viewer's two slates are not permutations",
      run: checks.m15ReelsOwnScorer,
    },
    {
      id: "M15.7",
      kind: "fn",
      desc: "not_dwelled emitted and used — exactly one row per settled impression, index 22, in the scorer's negative set",
      run: checks.m15NotDwelled,
    },
    {
      id: "M15.8",
      kind: "fn",
      desc: "request path still one read — M6 gate 9 + M13 gate 3 re-run unchanged",
      run: checks.m15ReadPathOneRead,
    },
  ],
  M16: [
    {
      id: "M16.1",
      kind: "fn",
      desc: "sandbox attribute byte-exact (allow-scripts allow-pointer-lock), never allow-same-origin; rule bites a srcDoc fixture",
      run: checks.m16SandboxAttr,
    },
    {
      id: "M16.2",
      kind: "fn",
      desc: "§2.8's five headers asserted on a real response through the Worker fetch path (SELF.fetch), incl. 404s",
      run: checks.m16CspHeaders,
    },
    {
      id: "M16.3",
      kind: "fn",
      desc: "over-budget GLB refused at ingest with the number reported; publish_artifact_version gated behind report.ok",
      run: checks.m16OverBudgetGlb,
    },
    {
      id: "M16.4",
      kind: "fn",
      desc: "MAX_LIVE_CONTEXTS = 2 holds — third acquireWebglSlot refused while two held, freed on release",
      run: checks.m16WebglBudget,
    },
    {
      id: "M16.5",
      kind: "fn",
      desc: "ticket verification does no database read — HYPERDRIVE absent from the artifact read path; Ed25519 mint/verify slice",
      run: checks.m16TicketNoDb,
    },
    {
      id: "M16.6",
      kind: "fn",
      desc: "no session reaches the frame — __Host-mb_session has no Domain=; sandboxed-frame spec asserts empty cookie + failed cross-origin reads",
      run: checks.m16NoSessionInFrame,
    },
    {
      id: "M16.7",
      kind: "fn",
      desc: "remix_root_id correct post-backfill — transitive root over a real app.fork_artifact chain; non-fork is self",
      run: checks.m16RemixRoot,
    },
    {
      id: "M16.8",
      kind: "fn",
      desc: "both new lint rules registered — index.js exports five, config all error, fixtures bite and counterparts pass",
      run: checks.m16LintRules,
    },
    {
      id: "M16.9",
      kind: "fn",
      desc: "musebook-artifacts still sealed — G-R2-SEAL re-run",
      run: checks.m16ArtifactsSealed,
    },
  ],
  M17: [
    {
      id: "M17.1",
      kind: "fn",
      desc: "held-out corpus: model beats deterministic pass rate, recorded with date (.gate/m17-comparison.json < 1 day old)",
      run: checks.m17Comparison,
    },
    {
      id: "M17.2",
      kind: "fn",
      desc: "validator gates model output identically; never-validating proposals end deterministic",
      run: checks.m17ValidatorGates,
    },
    {
      id: "M17.3",
      kind: "fn",
      desc: "gateway 503 → deterministic variant still produced; release_agent_spend returns the reservation",
      run: checks.m17GatewayDown,
    },
    {
      id: "M17.4",
      kind: "fn",
      desc: "zero unverified/null limits_source; every limits_checked_at within 90 days",
      run: checks.m17Provenance,
    },
    {
      id: "M17.5",
      kind: "fn",
      desc: "counter parity re-run across the widened platform set (all seeded rows)",
      run: checks.m17CounterParity,
    },
    {
      id: "M17.6",
      kind: "fn",
      desc: "new channels' deterministic variants are full ports; unpaywalled-copy consequence restated in fan-out review surface",
      run: checks.m17FullPorts,
    },
    {
      id: "M17.7",
      kind: "fn",
      desc: "REFORMAT_MODEL/REFORMAT_MAX_REPAIRS in manifest+wrangler vars; AI_GATEWAY_API_KEY a manifest secret, never a var",
      run: checks.m17EnvManifest,
    },
  ],
  M18: [
    {
      id: "M18.1",
      kind: "fn",
      desc: "WebMcpTools mounted as last child of /p/[slug]; import resolves @/components/post/webmcp-tools",
      run: checks.m18Mounted,
    },
    {
      id: "M18.2",
      kind: "fn",
      desc: "provider-present playwright: five post tools registered, all aborted on navigation",
      run: checks.m18Provider,
    },
    {
      id: "M18.3",
      kind: "fn",
      desc: "no provider: component contributes zero DOM (byte-identical by construction)",
      run: checks.m18Provider,
    },
    {
      id: "M18.4",
      kind: "fn",
      desc: "origin-trial meta renders only when NEXT_PUBLIC_WEBMCP_OT_TOKEN set; var in manifest on Vercel scope",
      run: checks.m18OriginTrial,
    },
    {
      id: "M18.5",
      kind: "fn",
      desc: "§7.20 checks 16+17: no-provider playwright green; zero navigator.modelContext hits",
      run: checks.m18Section720,
    },
    {
      id: "M18.6",
      kind: "fn",
      desc: "cite_passage writes exactly one citations row bound to content_hash + one agent_cite action_events row",
      run: checks.m18CiteWrites,
    },
    {
      id: "M18.7",
      kind: "fn",
      desc: "cite against ungranted post: 402, zero passage bytes (SECRET_MARKER), zero rows",
      run: checks.m18CiteDenied,
    },
    {
      id: "M18.8",
      kind: "fn",
      desc: "exactly one WebMCP integration point: component + register + mount only (set-equality)",
      run: checks.m18SingleIntegrationPoint,
    },
  ],
};

export const MILESTONE_TITLES = {
  M0: "Accounts, DNS delegation and resources",
  M1: "Monorepo, toolchain, CI, lint rules, and the gate runner",
  M2: "Schema, RLS, partitions, job_outbox, the musebook_worker role, and the deterministic seed",
  M3: "Identity and actor resolution in the Worker",
  M4: "@musebook/content",
  M5: "@musebook/kernel",
  M6: "musebook-edge read path",
  M7: "Compose, publish, mode picker, media upload",
  M8: "x402 v2 paywall in the Worker, grants, ledger, paid-media gate",
  M9: "musebook-mcp",
  M10: "Postiz sidecar + distributor",
  M11: "Telemetry: AE write path + Postgres rollups",
  M12: "Launch hardening",
  M13: "muse-mixer isolation + replay",
  M14: "Classification with Jev",
  M15: "Learned ranker v1.1",
  M16: "Artifacts surface + sandbox",
  M17: "LLM reformat pass + remaining channels",
  M18: "WebMCP progressive enhancement + agent citations",
  M19: "Media generation",
};
