-- supabase/migrations/20260922091901_platform_seed.sql   (M10; section 16.8)
-- The ONLY producer of platforms rows in production. Local-dev rows live in
-- supabase/seed.sql (section 17.3), never here.
insert into public.platforms (
  slug, display_name, postiz_identifier, max_chars, count_method, editor,
  min_media, max_images, max_videos, max_video_seconds, max_alt_chars,
  max_title_chars, supports_threads, max_thread_parts, supports_alt_text,
  supports_link_preview, max_hashtags, hashtag_style, requires_alt_text,
  url_counts_as_chars, stagger_seconds, concurrency_ceiling,
  analytics_supported, aspect_ratios, media_rules, limits_source,
  limits_checked_at, notes, updated_at
) values
  ('x','X','x',280,'x_weighted','html',
   0,4,1,140,1000,
   null,true,25,true,
   true,null,'inline',false,
   23,0,10,
   true,'["16:9","1:1","4:5"]'::jsonb,
   '{"images_or_one_video":true,"article_mode_images_only":true,"draft_article_no_replies":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'maxLength is dynamic: 4000 when the channel additionalSettings carries {title:"Verified",value:true}; 100000 when settings.post_type="article". The 4-media cap is NOT pre-validated by Postiz — it surfaces as a mapped API error. max_video_seconds and aspect_ratios are UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('linkedin','LinkedIn','linkedin',3000,'utf16','normal',
   0,20,1,600,300,
   null,false,null,true,
   true,null,'trailing',false,
   null,0,2,
   false,'["16:9","1:1","4:5"]'::jsonb,
   '{"carousel_min_images":2,"carousel_no_video":true,"video_max_total_media":1,"replies_text_only":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Postiz enforces: carousel needs >=2 images and no video; with a video, max 1 media total; COMMENTS MUST BE TEXT-ONLY. max_images 20, max_video_seconds, max_alt_chars are UNVERIFIED. linkedin-page is a separate channel identifier with the same 3000 limit and, unlike linkedin, WITH analytics.',
   '2026-09-21'::timestamptz),

  ('instagram','Instagram','instagram',2200,'utf16','normal',
   1,10,1,90,1000,
   null,false,null,true,
   false,30,'trailing',false,
   null,0,400,
   true,'["1.91:1","1:1","4:5"]'::jsonb,
   '{"requires_media":true,"carousel_max":10,"trial_reel_exactly_one_video":true,"audio_only_single_video_reel":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Postiz enforces >=1 media, carousel <=10, trial reel = exactly 1 video, audio never on a story. Aspect ratio 4:5..1.91:1 and the 1920x1080 cap appear ONLY as post-hoc error mappings in handleErrors, NOT as pre-flight checks. 30 hashtags and 90s reels are UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('tiktok','TikTok','tiktok',2000,'utf16','normal',
   1,35,1,600,null,
   90,false,null,false,
   false,null,'inline',false,
   null,0,10000,
   true,'["9:16"]'::jsonb,
   '{"requires_media":true,"multi_item_images_only":true,"video_must_be_single_item":true,"image_short_side_max_px":1080,"title_max":90}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Image short side <=1080px IS enforced (sharp). title @MaxLength(90) from TikTokDto. tiktok-business is a separate identifier at 2200 with up to 35 pictures. max_video_seconds UNVERIFIED. Most settings are silently discarded when content_posting_method=UPLOAD.',
   '2026-09-21'::timestamptz),

  ('youtube','YouTube','youtube',5000,'utf16','normal',
   1,0,1,null,null,
   100,false,null,false,
   false,null,'inline',false,
   null,0,200,
   true,'["16:9","9:16"]'::jsonb,
   '{"exactly_one_media":true,"must_be_mp4":true,"title_min":2,"title_max":100,"tags_total_chars_max":500,"tag_whitespace_surcharge":2}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Postiz enforces exactly 1 media and it MUST be .mp4. Title MinLength(2)/MaxLength(100). Tags cap is 500 chars TOTAL across all tags, +2 chars for any tag containing whitespace (YouTube quotes those). max_chars 5000 is the DESCRIPTION.',
   '2026-09-21'::timestamptz),

  ('threads','Threads','threads',500,'utf8_bytes','normal',
   0,10,1,300,1000,
   null,true,10,true,
   true,null,'inline',false,
   null,0,2,
   true,'["16:9","1:1","4:5"]'::jsonb,
   '{"carousel_supported":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'COUNTED IN UTF-8 BYTES, not characters: countLength() uses new TextEncoder().encode(text).length for this identifier only. Postiz has NO checkValidity override for threads, so no media rule is pre-validated. max_images 10 and 300s are UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('bluesky','Bluesky','bluesky',300,'graphemes','normal',
   0,4,1,180,null,
   null,true,25,true,
   true,8,'inline',false,
   null,0,2,
   false,'["16:9","1:1","4:5"]'::jsonb,
   '{"images_or_one_video":true,"applies_to_replies_too":true,"text_max_bytes":3000,"tags_max":8,"tag_max_graphemes":64,"image_max_bytes":2000000,"video_max_bytes":300000000}'::jsonb,
   'primary','2026-09-21',
   'app.bsky.feed.post lexicon: text maxGraphemes 300 AND maxLength 3000 bytes; tags maxLength 8, each maxGraphemes 64. app.bsky.embed.images: maxLength 4, image maxSize 2MB, alt REQUIRED on every image. app.bsky.embed.video: mp4 only, maxSize 300MB. NOTE Postiz counts this platform in UTF-16 code units, not graphemes — emoji-heavy text can pass Postiz and be rejected by Bluesky. Musebook counts graphemes. 180s is UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('mastodon','Mastodon','mastodon',500,'graphemes','normal',
   0,4,1,null,10000,
   null,true,25,true,
   true,null,'trailing',false,
   23,0,5,
   false,'[]'::jsonb,
   '{"per_instance_limits":true,"instance_config_endpoint":"/api/v2/instance"}'::jsonb,
   'primary','2026-09-21',
   'StatusLengthValidator::MAX_CHARS = 500, counted in GRAPHEME CLUSTERS, URL_PLACEHOLDER_CHARS = 23. Status::MEDIA_ATTACHMENTS_LIMIT = 4. MediaAttachment::MAX_DESCRIPTION_LENGTH = 10000. THESE ARE PER-INSTANCE: read configuration.statuses.max_characters, .characters_reserved_per_url and configuration.media_attachments.* from GET /api/v2/instance on connect and store as a channel override.',
   '2026-09-21'::timestamptz),

  ('reddit','Reddit','reddit',10000,'utf16','normal',
   0,20,1,null,null,
   300,false,null,false,
   true,null,'none',false,
   null,300,1,
   false,'[]'::jsonb,
   '{"subreddit_required":true,"title_min":2,"type_in":["self","link","media"],"media_type_exactly_one_media":true,"video_requires_thumbnail":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'RedditSettingsDtoInner: subreddit MinLength(2); title MinLength(2), NO max in the DTO; type in self|link|media; url @IsUrl when type=link. A media-type subreddit needs exactly 1 media and any .mp4 needs a thumbnail. CONCURRENCY 1 GLOBALLY (maxConcurrentJob=1) — stagger. max_images 20 and title 300 are UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('farcaster','Farcaster','wrapcast',1024,'utf8_bytes','normal',
   0,2,0,null,null,
   null,true,10,false,
   true,null,'inline',false,
   null,0,3,
   false,'[]'::jsonb,
   '{"images_only":true,"mp4_rejected":true,"embeds_max":2,"mentions_max":10,"long_cast_threshold":320}'::jsonb,
   'primary','2026-09-21',
   'POSTIZ IDENTIFIER IS "wrapcast", NOT "farcaster" — anything keyed by identifier must use wrapcast. Protocol SPECIFICATION.md: CastAddBody.text <= 1024 BYTES UTF-8; CastType.CAST for 0..320, CastType.LONG_CAST for 321..1024; embeds max 2; mentions max 10. Postiz caps at 800 in UTF-16 units, which is BOTH stricter and differently counted — Musebook uses 1024 bytes and lets Postiz''s own 800 check be the backstop. Postiz rejects any .mp4 in the post or any comment.',
   '2026-09-21'::timestamptz),

  ('discord','Discord','discord',1980,'utf16','markdown',
   0,10,1,null,null,
   null,false,null,false,
   true,null,'none',false,
   null,0,5,
   false,'[]'::jsonb,
   '{"webhook_posting":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Postiz maxLength is 1980, a deliberate margin under Discord''s documented 2000. EDITOR IS MARKDOWN. No checkValidity override, so no media rule is pre-validated. max_images 10 is UNVERIFIED.',
   '2026-09-21'::timestamptz),

  ('telegram','Telegram','telegram',4096,'utf16','html',
   0,10,1,null,null,
   null,false,null,false,
   true,null,'none',false,
   null,0,3,
   false,'[]'::jsonb,
   '{"caption_max_chars":1024,"zero_media_text_message":true,"one_media_caption":true,"multi_media_group":true}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'EDITOR IS HTML. Postiz uses 4096 uniformly, but Telegram''s Bot API caps a MEDIA CAPTION at 1024 while a plain text message is 4096. Postiz post() branches: 0 media -> text message; 1 media -> photo/video/document with the text as caption; >1 -> media group. Musebook''s validator therefore applies media_rules.caption_max_chars = 1024 whenever media is present. **UNVERIFIED:** the 1024 caption figure is from training data; core.telegram.org/bots/api was not reachable from this research environment. Safe fallback: the validator uses 1024 and the operator raises it only after reading the live Bot API page.',
   '2026-09-21'::timestamptz),

  ('pinterest','Pinterest','pinterest',500,'utf16','normal',
   1,5,1,null,null,
   100,false,null,true,
   true,null,'none',false,
   null,0,3,
   true,'["2:3","1:1"]'::jsonb,
   '{"requires_media":true,"max_media":5,"video_requires_exactly_two_items":true,"multi_image_identical_dimensions":true,"board_required":true,"title_max":100}'::jsonb,
   'postiz@v1.47.0','2026-09-21',
   'Postiz enforces 1..5 media; a video REQUIRES exactly 2 items (video + cover image as the second); multiple images must ALL share identical width AND height (sharp-measured). PinterestSettingsDto: title @MaxLength(100), board required. Aspect ratios are UNVERIFIED.',
   '2026-09-21'::timestamptz)
on conflict (slug) do update set
  postiz_identifier   = excluded.postiz_identifier,
  max_chars           = excluded.max_chars,
  count_method        = excluded.count_method,
  editor              = excluded.editor,
  min_media           = excluded.min_media,
  max_images          = excluded.max_images,
  max_videos          = excluded.max_videos,
  max_video_seconds   = excluded.max_video_seconds,
  max_alt_chars       = excluded.max_alt_chars,
  max_title_chars     = excluded.max_title_chars,
  supports_threads    = excluded.supports_threads,
  max_thread_parts    = excluded.max_thread_parts,
  supports_alt_text   = excluded.supports_alt_text,
  supports_link_preview = excluded.supports_link_preview,
  max_hashtags        = excluded.max_hashtags,
  hashtag_style       = excluded.hashtag_style,
  requires_alt_text   = excluded.requires_alt_text,
  url_counts_as_chars = excluded.url_counts_as_chars,
  stagger_seconds     = excluded.stagger_seconds,
  concurrency_ceiling = excluded.concurrency_ceiling,
  analytics_supported = excluded.analytics_supported,
  aspect_ratios       = excluded.aspect_ratios,
  media_rules         = excluded.media_rules,
  limits_source       = excluded.limits_source,
  limits_checked_at   = excluded.limits_checked_at,
  notes               = excluded.notes,
  updated_at          = now();
